### ISSUE TITLE
Mapear quais são os departamentos do Darcy Ribeiro

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#100]
# Descrição
Esta issue se dedica à encontrar e documentar (Em forma de comentários nesta issue) quais são os departamentos pertencentes ao campus Darcy Ribeiro.

# Tarefas
- [x] Pesquisar quais são os departamentos pertencentes ao Darcy Ribeiro.
- [x] Anotar os resultados da pesquisa.
- [x] Disponibilizar em forma de comentário nesta issue, os resultados obtidos.

# Critérios de aceitação
- [x] O link no qual foram encontrados os dados deve ser disponiblizado.
- [x] Os resultados encontrados devem ter sido expostos em forma de comentário nesta issue.
- [x] Os resultados encontrados devem ser revisados.

**Comment by lucasqueiroz23** [comment]
Foi realizada reunião no dia 31/03 para definir a estrutura do documento e desenvolvê-lo. Fizemos bom progresso, falta apenas a parte final. Participantes: @lucasqueiroz23 @mc-gomes

**Comment by laurapinos** [comment]
## Departamentos Darcy Ribeiro

Foi observado que, com relação ao campus Darcy Ribeiro, existem Departamentos e/ou Centros que compõem Faculdades/Institutos que se encontram no referido campus, com base no seguinte [organograma](http://www.dpo.unb.br/images/Imagens/organograma/202111/organograma_unb_outubro_2021.pdf). Dessa forma, estão descritas quais são as faculdades e institutos e seus respectivos componentes na tabela a seguir.

**Obs**: os outros campus da UnB - a saber: Gama (FGA), Ceilândia (FCE) e Planaltina (FUP) - também se enquadram estruturalmente como faculdades, porém, como o foco da pesquisa é o Darcy, os campus citados não constam na tabela.

|FACULDADE/INSTITUTO|DEPARTAMENTOS|CENTROS|
|-|-|-|
|FS - Faculdade de Ciências da Saúde|Enfermagem;<br />Odontologia;<br />Farmácia;<br /> Nutrição; <br /> Saúde Coletiva|NÃO POSSUI|
|FT - Faculdade de Tecnologia|Engenharia Civil e Ambiental;<br />Engenharia Elétrica;<br />Engenharia Florestal;<br /> Engenharia Mecânica; <br /> Engenharia de Produção|NÃO POSSUI|
|FACE - Faculdade de Economia, Administração, Contabilidade e Gestão de Políticas Públicas| Gestão de Políticas Públicas; <br />  Administração; <br />  Economia; <br />  Ciências Contábeis e Atuariais <br />|Centro Integrado de Ordenamento Territorial|
|FAU - Faculdade de Arquitetura e Urbanismo |Projeto, Expressão e Representação; <br /> Tecnologia em Arquitetura e Urbanismo; <br /> Teoria e História em Arquitetura e Urbanismo; |NÃO POSSUI|
|FAC - Faculdade de Comunicação|Audiovisuais e Publicidade; <br /> Jornalismo; <br /> Comunicação Social/Comunicação Organizacional |NÃO POSSUI|
|FE - Faculdade de Educação|Métodos e Técnicas;<br /> Planejamento e Administração; <br />Teoria e Fundamentos|NÃO POSSUI|
|FEF - Faculdade de Educação Física|Centro Olímpico|NÃO POSSUI|
|FM - Faculdade de Medicina|NÃO POSSUI|NÃO POSSUI|
|FD - Faculdade de Direito|NÃO POSSUI|NÃO POSSUI|
|FCI - Faculdade de Ciência da Informação|NÃO POSSUI|NÃO POSSUI|
|FAV - Faculdade de Agronomia e Medicina Veterinária|NÃO POSSUI|NÃO POSSUI|
|IB - Instituto de Ciências Biológicas|Biologia Celular;<br />Botânica;<br />Ciências Fisiológicas; <br /> Ecologia; <br /> Fitopatologia;<br /> Genética e Morfologia;<br /> Zoologia<br />|Nanotecnologia;<br />Primatologia|
|ICH- Instituto de Ciências Humanas|Filosofia; <br /> Geografia;<br />História;<br />Serviço Social|NÃO POSSUI|
|ICS - Instituto de Ciências Sociais|Sociologia;<br />Antrolpologia;<br />Estudos Latino-Americanos|NÃO POSSUI|
|IdA - Instituto de Artes|Artes Cênicas;<br />Artes Visuais;<br />Música;<br /> Design|NÃO POSSUI|
|IE - Instituto de Ciências Exatas|Ciência da Computação;<br /> Estatística; <br />Matemática|NÃO POSSUI|
|IG - Instituto de Geociências|NÃO POSSUI|Observatório Sismológico|
|IF - Instituto de Física|NÃO POSSUI|NÃO POSSUI|
|IPOL - Instituto de Ciências Políticas|NÃO POSSUI|NÃO POSSUI|
|IL - Instituto de Letras |Línguas Estrangeiras e Tradução; <br /> Linguística, Português e Línguas Clássicas; <br /> Teória Literária e Literatura|NÃO POSSUI|
|IP - Instituto de Psicologia|Psicologia Social do Trabalho; <br /> Psicologia Clínica; <br /> Psicologia Escolar e do Desenvolvimento;<br /> Processos Psicológicos Básicos|Centro De Atendimento E Estudos Psicológicos|
|IQ - Instituto de Química|NÃO POSSUI|NÃO POSSUI|
|IREL - Instituto de Relações Internacionais|NÃO POSSUI|NÃO POSSUI|

## REFERÊNCIAS BIBLIOGRÁFICAS
https://unb.br/estudante/institucional/estrutura-academica
http://www.dpo.unb.br/images/Imagens/organograma/202111/organograma_unb_outubro_2021.pdf
https://unb.br/estrutura-academica/faculdades
https://unb.br/estrutura-academica/institutos

**Comment by laurapinos** [comment]
A pesquisa foi documentada e aguarda revisão.

**Comment by Matheuspleal** [comment]
Excelente trabalho! todos os itens estão de acordo com o que está disposto nas documentações citadas. Acredito que, para este momento do projeto, o trabalho está mais que suficiente
