### ISSUE TITLE
Refatorar o script de scraping dos dados da FACULDADE DO GAMA - BRASÍLIA

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#101]
# Descrição
Nesta issue, os scripts criados para o scraping dos dados na FGA (Faculdade do Gama - Brasília) serão unidos e reorganizados para se tornarem um único arquivo.

# Tarefas
- [x] Unir os arquivos de scraping criados nas issues #93, #86 e #92.
- [x] Testar o script de scraping.
- [x] Relatar o aparecimento de bugs.
- [x] Correção dos bugs (Caso necessário).
- [x] Criação do arquivo único.
- [x] Deleção dos arquivos separados.

# Critérios de aceitação
- [x] Os arquivos devem ter sido unidos em um **único** script _python_.
- [x] Os bugs devem ter sido tratados.
- [x] Postagem (em forma de comentários) dos problemas encontrados e das decisões tomadas.

**Comment by oCaioOliveira** [comment]
# Ata da Reunião 
Reunião realizada dia 30/03 com participação de @lucasqueiroz23, @vitorekr e @oCaioOliveira. Houve uma tentativa de refatoração do código para um único arquivo e tivemos um impedimento em relação ao que o código retorna, sendo incompatível com o banco de dados. Haverá outra reunião com aspecto geral para falar sobre as dificuldades e tentar corrigi-las o quanto antes.

**Comment by AdneMoretti** [comment]
Boa tarde galera, acho que essa issue já foi resolvida com a issue #125 , se vocês quiserem dar uma olhada, inclusive, está com PR aberto. Lá juntei todos os dados necessários para os nossos modelos do banco de dados. Porém, se vocês quiserem organizar as funções em uma classe ou algo do tipo, isso ainda não foi feito

**Comment by oCaioOliveira** [comment]
Essa issue foi resolvida por meio da issue #125 e está sendo fechada por conta dos seus critérios de aceitação já estarem sendo sanados.
