### ISSUE TITLE
Criação do arquivo '.gitignore'

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#104]
# Descrição
Nesta issue, o arquivo '.gitignore' será criado e será adicionado o 'geckodriver.log' ao conteúdo do mesmo.

# Tarefas
- [x] Criar o arquivo '.gitignore'.
- [x] Adicionar o arquivo 'geckodriver.log' ao '.gitignore'.

# Critérios de aceitação
- [x] Arquivo '.gitignore' criado.
- [x] Adição do arquivo à branch _**develop**_.
- [x] Arquivo '.gitignore' revisado.

**Comment by Matheuspleal** [comment]
O arquivo '.gitignore' foi adicionado à branch _**develop**_ e aguarda revisão.

**Comment by gabrielm2q** [comment]
'.gitignore' adicionado corretamente.

**Comment by Matheuspleal** [comment]
Conforme revisão do @gabrielm2q , estarei fechando esta issue.
