### ISSUE TITLE
Criação do requirements.txt

### ISSUE THREAD

**Issue by vitorekr** [fga-eps-mds/2021.2-INDICAA#114]
# Descrição
Criação do requirements.txt para facilitar a instalação de bibliotecas e compatibilidade de versões durante o desenvolvimento do sistema.

# Tarefas
- [x] Criar documento texto.
- [x] Adicionar bibliotecas usadas no desenvolvimento do projeto.
- [x] Inserir o documento texto na pasta src do projeto.

# Critérios de aceitação
- [x] Documento deve ser revisado.

**Comment by vitorekr** [comment]
A criação desse documento tem como objetivo inserir um documento chamado requirements.txt, que facilita a instalação das bibliotecas necessárias para o desenvolvimento do projeto. Com o documento texto inserido na nas pastas do código, basta que a pessoa mude o diretório para onde se encontra o documento "requirements.txt" com o ambiente virtual ativado e dar o comando "pip install -r requirements.txt", fazendo, assim, com que as bibliotecas e versões sejam padronizadas.

**Comment by vitorekr** [comment]
Aqui está algumas bibliotecas. Quem for revisar e conseguir identificar alguma biblioteca que está faltando pode nos avisar.
[requirements.txt](https://github.com/fga-eps-mds/2021.2-INDICAA/files/8409527/requirements.txt)

**Comment by AdneMoretti** [comment]
Bom dia Vitor! Acho que pode adicionar também o django e django rest framework no arquivo.

**Comment by vitorekr** [comment]
> Bom dia Vitor! Acho que pode adicionar também o django e django rest framework no arquivo. Tem também o pytest, que usaremos para testes.

Opa, acabei de adicionar essas, valeu!

**Comment by vitorekr** [comment]
requirements.txt adicionado e foi dado o commit.
