### ISSUE TITLE
Realizar o deploy da API no servidor (Heroku, etc..)

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#116]
# Descrição
Esta issue se dedicará ao deploy da API criada com Django Rest em um servidor.

# Tarefas
- [x] Conectar o scraping à API.
- [x] Fazer o deploy da API no servidor.
- [ ] Listar o passo a passo feito em forma de comentários nesta issue.

# Critérios de aceitação
- [x] Link para o servidor com a API.
- [x] Deploy testado e funcionando corretamente

**Comment by oCaioOliveira** [comment]
Feito o deploy da API no heroku e disponibilizada no link [API Indicaa](https://indicaa-unb-apii.herokuapp.com/).

**Comment by Matheuspleal** [comment]
O passo a passo será listado aqui nos comentários da issue durante a sprint 13.
