### ISSUE TITLE
Criar de um dashboard de exmplo.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#117]
# Descrição
Nesta issue, será criado um dashboard de exemplo após a conexão do banco de dados de teste ao metabase pela issue #102.

# Tarefas
- [x] Listar passo a passo para a criação de um dashboard.
- [x] Criar o dashboard com os dados oferecidos pelo banco de dados.

# Critérios de aceitação
- [x] Dashboard criado e disponível para acesso no [metabase do projeto](https://indicaa.herokuapp.com/).
- [x] Passo a passo colocado em forma de comentário nesta issue.

**Comment by LeticiaAires** [comment]
Segue o passo a passo feito por @Eruel6 e @LeticiaAires 
1 -> na pagina do metabase na seção de "our analitics" clique em "browse all items" para abrir a visão de todos os dashboards 

2 -> para criar um novo dashboard clique no "+" no canto superior direito da pagina e selecione a opção question

3 -> quando entrar na pagina inicial da criação das questions, selecione o banco de dados a ser utilizado.

4 -> após entrar na pagina de criação da question no campo data o dado a ser trabalhado ( ex pessoa, review...)

5 -> quando selecionado o dado basta adicionar os filtros pertinentes.

6 -> na parte de sumarize escolha o dado que gostaria de ver 

7 -> após tudo feito clique em vizualise, se os dados estiverem aparecendo de forma correta, basta clicar para adicionar em um dashboard ou criar um novo.

**Comment by Matheuspleal** [comment]
O processo descrito está correto, portanto os critérios de conclusão da issue foram cumpridos.
