### ISSUE TITLE
Dockerização da API

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#118]
# Descrição
Esta issue se dedicará a dockerização da API, para que a mesma se encontre em ambiente configurado e propício para seu próprio funcionamento.

# Tarefas
- [x] Criação do arquivo dockerfile e docker-compose.yml
- [x] Configuração da imagem do postgresql 
- [x] Configuração para rodar o servidor da api  e o db ao subir o docker com : `sudo docker-compose up`

# Critérios de aceitação
- [x] A issue ter sido revisada
- [x] O servidor estar subindo corretamente ao rodar: `sudo docker-compose up`
- [x] A aplicação não apresentar erros.

**Comment by MorettiGS** [comment]
# Concatenação de issues

Estaremos realizando, na branch `feature/(#126)-configuracao-postgresql`, as tarefas referentes à issue #118 e à issue #126, assim completando ambas as issues simultaneamente.

**Comment by AdneMoretti** [comment]
Fiz algumas alterações no dockerfile e no docker-compose.yml para arrumar erros que estavam aparecendo ao subir o docker. No dockerfile, foi alterada a seguinte linha:
`ENV DJANGO_SETTINGS_MODULE=config.settings`, troquei  'app' por 'config', pois é a pasta correta em que o settings se localiza.
Já em docker-compose.yml, alterei as seguintes linhas:
```
environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
 ```
```
        volumes:
               - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
```
Pois o docker estava apresentando erro ao acessar a porta 5432 e com o password.

Com essas alterações, o ambiente está subindo sem erros. Para finalizar a issue, deve ser discutida a adição e configuração do metabase no docker.

**Comment by gabrielm2q** [comment]
Conseguimos instalar o firefox no container a partir do Dockerfile.

**Comment by gabrielm2q** [comment]
O banco de dados teve alguns campos com tamanho ampliado para receber dados com maior extensão.
A dockerização foi realizada e o comando "docker-compose up" roda normalmente.

A issue está pronta para revisão.

Membros que atuaram na correção:
@AdneMoretti
@MorettiGS
@Matheuspleal
@guibrbs
@gabrielm2q

**Comment by AdneMoretti** [comment]
A issue está com PR aberto, pois todas as configurações necessárias foram feitas, acrescentamos a imagem do metabase, que está rodando atualmente na porta 3000. Além disso, os problemas relacionados ao comando migrate também foram resolvidos.

**Comment by AdneMoretti** [comment]
A issue de dockeirização já está na branch develop, para subir a aplicação, basta rodar o seguinte comando `sudo docker-compose up`. Sendo assim, issue concluída e fechada.
