### ISSUE TITLE
Finalização do desenvolvimento do novo git pages (wiki)

### ISSUE THREAD

**Issue by Matheuspimentell** [fga-eps-mds/2021.2-INDICAA#119]
# Descrição
Esta issue será dedicada à continuidade do desenvolvimento do git pages que foi inicado na issue #90.

# Tarefas
- [x] Realizar o deploy do novo git pages.
- [x] Adicionar as documentações existentes.
- [x] Atualizar os links para o git pages.

# Critérios de aceitação
- [x] Git pages com o deploy feito no novo repositório.
- [x] Documentações atualizadas.
- [x] Links para o git pages atualizados nos 2 repositórios.

**Comment by guibrbs** [comment]
O GitHub Pages do projeto teve sua continuidade, conseguimos executar boa parte do protótipo disponibilizado na issue #90. Até então falta somente adicionar as documentações, arrumar a responsividade para tablet, e realizar o deploy.

**Comment by guibrbs** [comment]
Todas as documentações presentes no antigo GitPages foram adicionadas no novo, localizado no repositório Wiki, incluindo na branch gh-pages.

**Comment by guibrbs** [comment]
Foi realizado o deploy do novo GitHub Pages no repositório wiki, e o link para o site será disponibilizado tanto no repositório INDICAA quanto no Wiki

**Comment by guibrbs** [comment]
O link para o GitHub Pages foi atualizado nos dois repositórios.

**Comment by guibrbs** [comment]
Todas as documentações foram adicionadas no novo GitHub Pages.
