### ISSUE TITLE
Colocar as documentações atuais no novo git pages

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#120]
# Descrição
O novo git pages vai estar sem as documentações em seu conteúdo. O objetivo desta issue é colocar as documentações no gitpages de forma clara e visual.

# Tarefas
- [x] #123 .
- [x] Fazer uma lista de documentações gerais e de grupo.
- [x] Colocar todas as documentações da lista de forma organizada e visual no novo git pages.

# Critérios de aceitação
- [x] Todas as documentações devem estar no novo repositório.
- [x] A lista com as documentações existentes e faltantes deve estar em forma de comentários nesta issue.
- [x] As documentações existentes e listadas devem estar no novo git pages de forma organizada e visual.

**Comment by guibrbs** [comment]
## Lista de documentações:
- Dicionário de dados
- Documento de Arquitetura
- Documento de Metodologia
- Documento de Requisitos
- Documento de Visão
- Estrutura analítica do projeto
- Gerenciamento de Comunicação
- Gerenciamento de Riscos
- Guia de branching
- Guia de estilo 
- Protótipos
- Termo de Abertura
- Guia de Contribuição
- Atas do grupos com as sprints
- Template de Commit
- Layout de sprint
- Template de issue

**Comment by guibrbs** [comment]
Algumas documentações já foram colocadas no GitPages, ficaram como dívida as seguintes:
- Dicionário de dados
- Guia de estilo
- Guia de branching
- Template de Commit

**Comment by guibrbs** [comment]
Foram feitos dois deploys, o primeiro adicionando as seguintes documentações ao GitHub Pages

> Algumas documentações já foram colocadas no GitPages, ficaram como dívida as seguintes:
> 
> * Dicionário de dados
> * Guia de estilo
> * Template de Commit
> * Sprint Layout
> * Issue Template

E o segundo adicionando o código de conduta, que por sua via, também estava com pendência.
