### ISSUE TITLE
Guardar dados de scraping no banco de dados

### ISSUE THREAD

**Issue by AdneMoretti** [fga-eps-mds/2021.2-INDICAA#125]
# Descrição
Essa issue tem como objetivo pegar os dados de scraping da Faculdade do Gama já obtidos em `src/scraping/QtdeAlunosMatriculados.py`. Se necessário, também é possível refatorar as funções de scraping para se adequar aos modelos do banco de dados.

# Tarefas
- [x] Pesquisar maneiras de colocar dados no banco de dados.
- [x] Pegar os dados do scraping e colocar dentro do banco de dados do projeto através do Django ORM.

# Critérios de aceitação

- [x] O código ter sido revisado.
- [x] O código estar dentro da develop.
- [x] Código testado e funcionando e populando o db com os dados.

**Comment by vitorekr** [comment]
Encontrei um site interessando explicando sobre como colocar dados de scraping no MongoDB.
Link: https://alysivji.github.io/mongodb-pipelines-in-scrapy.html

**Comment by vitorekr** [comment]
Encontrei um site explicando bem como inserir dados de scraping dentro do banco de dados(PostgreSQL).
Link: https://kb.objectrocket.com/postgresql/scrape-a-website-to-postgres-with-python-938

**Comment by AdneMoretti** [comment]
Para testar e revisar o código acima, é necessário seguir os seguintes passos:
Após entrar na branch, rodar os seguintes comandos
```
cd src
cd indicaa-api
pip install requirements.txt
python manage.py runserver
```
Os comandos `pip` e `python`, podem ser subsituidos por `pip3` e `python3`.
O servidor estará iniciando e fazendo o scraping, depois basta clicar no link ou entrar no localhost:8000, e verificar se os dados de sraping estão no db.

**Comment by vitorekr** [comment]
Estava analisando o código, e todos os 6 tópicos sinalizados estão de acordo e os dados estão sendo colocados dentro do banco de dados.

**Comment by AdneMoretti** [comment]
Issue já revisada e dentro da develop. Sendo assim, já foi concluída.
