### ISSUE TITLE
Mudar configurações da api para PostgreSQL

### ISSUE THREAD

**Issue by AdneMoretti** [fga-eps-mds/2021.2-INDICAA#126]
# Descrição
O objetivo dessa issue é mudar as configurações da API para o banco de dados PostgreSQL. Atualmente, as configurações de database em `indicaa-api/config/settings.py` estão para o SQLite.

# Tarefas
- [x] Pesquisar como alterar as configurações.
- [x] Configurar o PostgreeSQL.
- [x] Verificar se o banco de dados está funcionando e se está guardando os dados.
- [x]  As alterações devem ser descritas em forma de comentário nessa issue.

# Critérios de aceitação
- [x] O código alterado estar dentro da branch develop.
- [x] A issue ter sido revisada.
- [x] O banco de dados estar funcionando.

**Comment by MorettiGS** [comment]
# Migração

Para completar o objetivo da issue, primeiro foi preciso encontrar quais seriam as exatas configurações a serem alteradas.
Encontramos, portanto, a seguinte seção do arquivo `indicaa-api/config/settings.py`:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
```

Referenciando o banco de dados SQLite. Portanto, após pesquisa, foi feita a seguinte mudança:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
```
Com isso, estaríamos criando um banco de dados que referencie o PostgreSQL.

Entretanto, visto que o resto do programa foi feito com base no SQLite, foi necessária uma migração para o PostgreSQL no geral, feita com sucesso.

# Teste

Para conseguir testar, realizamos a inserção de alguns dados na API resultante e conferimos se tais dados persistiam após a reinicialização da API. O teste foi feito com sucesso.

**Comment by MorettiGS** [comment]
# Mudanças adicionais

Foi percebido que o código continha dois arquivos `requirements.txt`, portanto eles foram concatenados em um só arquivo de mesmo nome.

Também foi criado um usuário para o PostgreSQL, para que seja possível acessar o servidor corretamente.

**Comment by MorettiGS** [comment]
# Concatenação de issues

Estaremos realizando, na branch `feature/(#126)-configuracao-postgresql`, as tarefas referentes à issue #118 e à issue #126, assim completando ambas as issues simultaneamente.

**Comment by AdneMoretti** [comment]
O banco de dados já foi configurado e já está mergeado com a branch develop, sendo assim, issue está sendo fechada.
