### ISSUE TITLE
Revisão dos documentos presentes no repositório: fga-eps-mds/2021.2-INDICAA-Wiki

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#129]
# Descrição
Esta issue se dedicará à revisar os novos e os atuais documentos presentes no repositório fga-eps-mds/2021.2-INDICAA-Wiki.

# Tarefas
- [x] Revisar os arquivos, procurando mais erros ou inconsistências.
- [x] Realizar as correções gramaticais sugeridas no PR fga-eps-mds/2021.2-INDICAA-Wiki#4.
- [x] Criar um Pull Request partindo da branch develop para a branch main, para que os arquivos revisados estejam atualizados no [novo git pages](https://fga-eps-mds.github.io/2021.2-INDICAA-Wiki/).

# Critérios de aceitação
- [x] Todas as correções gramaticais devem ter sido feitas.
- [x] Novos erros devem ter sido corrigidos.

**Comment by LeticiaAires** [comment]
As devidas correção gramaticais referentes ao PR fga-eps-mds/2021.2-INDICAA-Wiki#4. foram executadas

**Comment by LeticiaAires** [comment]
- [ ] No tópico 3 do termo de abertura do projeto, cabe o uso da vírgula após o vocábulo "geral";
- [ ] Na linha 37 do termo de abertura do projeto, pode-se trocar "desse" por 'do';
- [ ] Na linha 15 do documento de protótipos está escrito "protóripos";
- [ ] Na linha 105 do documento de metodologia sugiro que invertam "consulta posterior" por "posterior consulta";
- [ ] Na linha 93 do documento de metodologia está escrito "ferramentar";
- [ ] Na linha 60 do documento de visão, deve-se retirar a crase, tendo em visa que antecede um verbo no infinitivo;
- [ ] Na linha 28 do documento de arquitetura, pode-se trocar "desse" por "do"
- [ ] Na linha 48 do documento de arquitetura não convém o uso do "." que antecede o vocábulo "e"

**Comment by Matheuspleal** [comment]
As atualizações foram feitas e o PR foi feito: fga-eps-mds/2021.2-INDICAA-Wiki#15
