### ISSUE TITLE
Elaborar os testes necessários para o backend

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#135]
# Descrição
Nesta issue, serão elaborados os testes necessários para comprovar a qualidade do software produzido pela equipe INDICAA.

# Tarefas
- [x] Escrever os testes do script de scraping.
- [x] Escrever os testes do Banco de dados.
- [x] Escrever os testes da API.

# Critérios de aceitação
- [x] Testes do scraping postados em uma pasta própria para os testes no repositório.
- [x] Testes do banco de dados postados em uma pasta própria para os testes no repositório.
- [x] Testes da API postados em uma pasta própria para os testes no repositório.

**Comment by MorettiGS** [comment]
# Execução

Para executar os testes, certifique-se de estar na pasta ```./src/indicaa-api/```.

Quando na pasta, é possível realizar o comando ```pytest``` no terminal para executar os testes.

**Comment by AdneMoretti** [comment]
Acabei de adicionar alguns testes para o backend do projeto, entre eles, teste para o crud de materias e turmas. Com a atualização com a develop, os seguintes passos são necessários pra executar os testes.
```
docker-compose up
```
Após rodar esse comando, deixe-o rodando e abra outro terminal na sua ide, nesse:
```
docker-compose exec indicaa bash
```
Isso irá abrir o bash do docker, depois basta entrar nas pastas com:
```
cd src/indicaa-api
pytest
```
