### ISSUE TITLE
Completar seções faltantes do documento de arquitetura.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#136]
# Descrição
No momento existem seções à completar no documento de arquitetura. O objetivo desta issue é preencher estas seções com as informações necessárias.

# Tarefas
- [x] Retirar formatações html desnecessárias dos documentos Markdown. [Tags <a> antes dos títulos, tags <p> ao iniciar uma seção]
- [x] Melhorar a formatação markdown do doc. de arquitetura.
- [x] Revisar o diagrama de casos de uso (Tópico 4.1).
- [x] Inserir o diagrama de casos de uso (Tópico 4.1). 
- [x] Refazer o diagrama de pacotes (Tópico 5.2).
- [x] Inserir dados da seção de Visão de implementação (Tópico 6).
- [x] Representação da arquitetura (Tópico 2).
- [x] Tecnologias (Tópico 2.1).
- [x] Visão geral (Tópico 5.1).

# Critérios de aceitação
- [x] Todos as tarefas acima terem sido completadas.
- [x] O documento de arquitetura atualizado deve estar disponível na branch develop do repositório 2021.2-INDICAA-Wiki, pronto para ser colocado na branch main do repositório 2021.2-INDICAA-Wiki.

**Comment by LeticiaAires** [comment]
Foram feitas correções tanto nas formatações markdown, quanto HTML, além disso o diagrama de casos de uso foi revisado e inserido. Por fim, foram incluídas as ferramentas e linguagens utilizadas para desenvolvimento do software.
Peço que revise, porque posso ter deixado escapar alguma coisa.
Qualquer coisa, é só falar! @Matheuspleal

**Comment by Matheuspleal** [comment]
# Versão 1 do diagrama de pacotes atualizado
![Diagrama em branco - Página 1 (1)](https://user-images.githubusercontent.com/62526025/164501568-30b8279f-9d31-461c-a262-96ca6cc981f3.png)

**Comment by Matheuspleal** [comment]
Irei inserir a descrção arquitetural de cada tecnologias citada no tópico 2.1

**Comment by Matheuspleal** [comment]
Falta apenas adicionar o tópico 6, mas este só será possível imediatamente antes da criação das release notes

**Comment by Matheuspleal** [comment]
O PR foi criado para a conclusão da issue.
