### ISSUE TITLE
🐛 Consertar a formatação de documentos no git pages 

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#137]
**Descreva o bug**
Existem alguns documentos que estão com a formatação em markdown errada. ```listar arquivos```
 

**Passo a passo para a reprodução do bug**

Para reproduzir o bug, siga os passos:
1. Vá até o [git pages do projeto](https://fga-eps-mds.github.io/2021.2-INDICAA-Wiki/).
2. Clique em Produto.
3. Selecione o documento de visão.
4. Veja o bug a partir do tópico 4.

**Comportamento esperado**
O comportamento esperado é de que o mesmo se encontre da mesma forma que estava em seu formato markdown.

**Screenshots**
![image](https://user-images.githubusercontent.com/62526025/163893849-e012dd26-16a2-4ee6-bfe5-8252e60c2e50.png)

**Comment by guibrbs** [comment]
O bug foi corrigido. Identificamos alguns erros de tags HTML que não estavam sendo devidamente fechadas e seu uso era irrelevante, portanto, foram retiradas. Outra correção de bug foram espaços desnecessários antes de títulos e subtítulos.

**Comment by Matheuspleal** [comment]
Foram consertados vários erros de formatação em diversos documentos do projeto.

**Comment by Matheuspleal** [comment]
Com o PR fga-eps-mds/2021.2-INDICAA#19 aceito, a formatação dos documentos só será revisada na branch develop.
