### ISSUE TITLE
Inserir as screenshots dos protótipos no git pages.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#138]
# Descrição
O documento de protótipos está com links para comentários nas issues que mostram as imagens dos protótipos. O objetivo desta issue é inserir essas imagens no lugar dos links.

# Tarefas
- [x] Inserir as screenshots todos os protótipos citados pelo [documento de protótipos](https://fga-eps-mds.github.io/2021.2-INDICAA-Wiki/documentacao/prototipos/) no git pages.
- [x] Inserir os protótipos feitos no figma.
- [x] Remover os links

# Critérios de aceitação
- [x] As screenshots devem estar disponíveis no novo git pages.
- [x] Todos os links que levam para imagens de protótipos devem ser retirados

**Comment by guibrbs** [comment]
As alterações foram feitas seguindo as tarefas, inserimos as screenshots dentro da seção "Protótipo de baixa fidelidade".
Já dentro do "Protótipo de alta fidelidade", inserimos um breve resumo, e o motivo para não desenvolver um front-end para o projeto, mas sim em desenvolver o GitHub Pages a partir do MkDocs Material. Dentro dessa seção referenciamos também o link para o Figma, com os protótipos feitos pela a equipe.

**Comment by guibrbs** [comment]
Toda alteração foi realizada na branch "feature/(#138)-prototipos", seguirá para um Pull Request para a branch develop e posteriormente para a main.
