### ISSUE TITLE
Inserir aba de release notes no git pages

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#139]
# Descrição
Atualmente, o acesso à documentação da release está sendo feito por meio da interface do github. O objetivo desta issue é disponbilizar as release notes no git pages do projeto, visto que as mesmas são parte fundamental da documentção

# Tarefas
- [x] Criar seção para as release notes.
- [x] Inserir a release notes da release 1 (v0.1).

# Critérios de aceitação
- [x] As release notes devem estar disponíveis no git pages do projeto.
- [x] As release notes devem possuir sua própria seção no header do git pages.

**Comment by guibrbs** [comment]
A seção de release notes foi devidamente criada e nela foi inserido o documento da release 1 e posteriormente será adicionado o da release 2 conforme sua criação.
As modificações já foram commitadas seguindo nossa [política de branch](https://github.com/fga-eps-mds/2021.2-INDICAA-Wiki/blob/main/docs/documentacao/guia_de_branching.md) e seguirá para o PR para a branch develop.

**Comment by guibrbs** [comment]
As seguintes alterações foram feitas dentro do mkdocs.yml:
```
- Release Notes:
   - Release 1: release_notes/release1_notes.md
```
Referenciando a criação de uma nova pasta "release_notes", juntamente com o arquivo em markdown para ser reproduzido dentro do GitHub Pages. 
As alterações já estão na branch develop e posteriormente seguirão um Pull Request para a main.
