### ISSUE TITLE
Elaboração das instruções de execução do projeto.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#141]
# Descrição
O README.md do projeto precisa conter as instruções de instalação execução das versões de desenvolvimento (local) e versões oficiais (Releases).

# Tarefas
- [x] Elaborar instruções de instalações prévias (tecnologias).
- [x] Elaborar instruções de instalações no linux.
- [x] Elaborar instruções de execuções no linux,
- [ ] ~Elaborar instruções de intalações no windows.~
- [ ] ~Elaborar instruções de execuções no windows.~
- [ ] ~Elaborar seção de "outros SO's"~

# Critérios de aceitação
- [x] As instruções de instalações prévias devem ser elaboradas corretamente e colocadas na branch de desenvolvimento do repositório 2021.2-INDICAA-Wiki.
- [x] As instruções de execuções devem ser elaboradas corretamente e colocadas na branch de desenvolvimento do repositório 2021.2-INDICAA-Wiki.
- [x] Todas as tarefas citadas devem ser completadas.

**Comment by guibrbs** [comment]
Foram elaboradas as instruções de execução do projeto no repositório Wiki, nela abordamos os seguintes tópicos:
- Instalações das tecnologias necessárias para rodar o projeto
   - Docker 
   -  Python
- Execução
   - GitHub Pages
      - Adicionamos instruções a partir do python para instalar o mkdocs-material e o mkdocstrings
   - API
      - Adicionamos instruções a partir do docker, com o ```docker-compose up```
   - Metabase
      - O metabase já estará rodando a partir da API, porém reforçamos que é preciso ser feito uma configuração prévia

**Comment by guibrbs** [comment]
Como o README já estava muito extenso e com instruções repetidas para Windows e Ubuntu, decidimos não incluir as instruções do Windows.

**Comment by guibrbs** [comment]
O PR para a branch develop foi feito, seguirá para revisão.
