### ISSUE TITLE
Gerar Release Notes

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#143]
# Descrição
Com a deadline para a Release 2 se aproximando, é necessária a criação das _**Release Notes**_ para que haja melhor entendimento sobre o que foi feito no projeto durante o tempo hábil.

# Tarefas
- [x] Descrever as versões das tecnologias.
- [x] Descrever todas as documentações adicionadas / Melhoradas.
- [x] Incluir uma seção de features adicionadas ao projeto.
- [x] Incluir uma seção de bug fixes.

# Critérios de aceitação
- [x] Escrever as _**release notes**_ no formato markdown para que também possa ser colocado no git pages.
- [x] Salvar as release notes no repositório wiki do projeto, seguindo os padrões de nomenclatura e sistema de arquivos estabelecidos.

**Comment by Matheuspleal** [comment]
As release 2 notes foram inciadas e serão refatoradas conforme necessário

**Comment by Matheuspimentell** [comment]
Release notes geradas corretamente e colocadas no repositório
