### ISSUE TITLE
Escrever o documento Post Mortem.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#145]
# Descrição
Com a finalização dos trabalhos da disciplina, **cada** grupo deve gerar sua documentação Post Mortem, para que seja possível o acompanhamento e análise futura sobre o processo que foi executado durante o projeto INDICAA.

# Tarefas
- [x] Escrever Post Mortem (**Cada grupo deve escrever seu Post Mortem**).
- [x] Salvar o documento Post Mortem no repositório Wiki do projeto, seguindo as regras de nomenclatura e de sistemas de arquivos deifinidas.
- [x] Ficar com saudades do projeto 😢

# Modelo a ser adotado

Por orientação da professora Carla, o modelo de post mortem a ser adotado será o do [projeto Anunbis](https://fga-eps-mds.github.io/2020.2-Anunbis/). E ele se encontra a seguir:

```md
# Post Mortem

## Introdução

Este documento tem por finalidade fornecer uma avaliação crítica quanto ao projeto,
realizado na etapa final, é de suma importância sua leitura, pois ele contém informações cruciais para auxiliar no desenvolvimento de projetos futuros.

## Pontos do projeto

### Positivos

-   .
-   .
-   .
-   .

### Negativos

-   .
-   .
-   .

## Conselhos para projetos futuros

-   .
-   .
-   .
-   .

<!-- Nesta seção, seguir a ordem de cargos que desejar -->
## Feeling Individual

### Product Owner

texto

gif

### Dev

texto

gif

### DevOps

texto

gif

### Arquiteto

texto

gif

### Scrum Master

texto

gif
```

# Critérios de aceitação
- [x] Post Mortem do grupo 01 criado e inserido no git pages.
- [x] Post Mortem do grupo 03 criado e inserido no git pages.
- [x] Post Mortem do grupo 04 criado e inserido no git pages.

## Um enorme agradecimento à todos que colaboraram e deram o seu melhor para o projeto! O projeto INDICAA acabou, mas os aprendizados, risadas e amizades criadas ficarão para sempre.

**Comment by MorettiGS** [comment]
# Conclusão

O Post Mortem foi concluído por todos os grupos corretamente, assim completando a issue.
