### ISSUE TITLE
Adicionar "Code of conduct" no repositório

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/2021.2-INDICAA#24]
# Descrição
Fazer o documento de código de conduta para o projeto

# Tarefas
- [x] Criação do documento 

# Critérios de aceitação
- [x] Documento Criado
- [ ] Documento revisado e as suas devidas análises comentadas nesta _issue_
- [x] .MD adicionado ao repositório

**Comment by guigudf** [comment]
Link que pode se usado como base pra criação do documento
https://github.com/fga-eps-mds/2021.1-AlligaBot/blob/main/docs/_posts/2021-08-21-code_of_conduct.md

**Comment by Matheuspleal** [comment]
[Code of coduct do TensorFlow](https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md)

**Comment by gabrielm2q** [comment]
[Microsoft Open Source - Code of Conduct](https://opensource.microsoft.com/codeofconduct/)
[Swift - Code of Conduct](https://github.com/apple/swift/blob/main/CODE_OF_CONDUCT.md)
[Contributor Covenant](https://www.contributor-covenant.org/): código de conduta utilizado em vários projetos Open Source.

**Comment by MorettiGS** [comment]
Alguns códigos de conduta dos projetos realizados na matéria de MDS/EPS, que poderiam auxiliar a criação do documento:

[Code of Conduct - Acacia](https://github.com/fga-eps-mds/2019.2-Acacia-Frontend/blob/develop/CODE_OF_CONDUCT.md)
[Code of Conduct - SysArq](https://github.com/fga-eps-mds/2021.2-SysArq-Frontend/blob/main/CODE_OF_CONDUCT.md)
[Code of Conduct - Amika](https://github.com/fga-eps-mds/2019.2-Amika-Frontend/blob/develop/CODE_OF_CONDUCT.md)

**Comment by Matheuspleal** [comment]
Foi criada a nova branch "code-of-conduct" para trabalho colaborativo de todos os envolvidos

**Comment by gabrielm2q** [comment]
Atualizei a parte dos "Nossos Padrões" do Código de Conduta. Conteúdo sujeito a revisão.

**Comment by joaopaulob3** [comment]
Pessoal, atualizei e revisei o nosso [CODE_OF_CONDUCT.md](https://github.com/fga-eps-mds/Projeto01/blob/code-of-conduct/CODE_OF_CONDUCT.md). Peço que verifiquem se atende aos critérios e se ele necessite de mais alguma modificação. Só tenho uma pergunta: é realmente necessário ter a parte em inglês no nosso .md?

**Comment by guibrbs** [comment]
Pessoal, fiz também uma revisão do documento e fiz apenas uma alteração referente a erro de ortografia.

**Comment by Matheuspleal** [comment]
Versão final do documento adicionada ao repositório na branch code-of-conduct. Resta o merge entre esta e a branch main.

**Comment by Matheuspleal** [comment]
Código de conduta adicionado e finalizado.
