### ISSUE TITLE
Treinamento de React, HTML, CSS

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#28]
# Descrição
Reunião dos grupos para treinamento das tecnologias específicas decididas pelo time.

# Tarefas
- [x] Treinamento Front-End (React)

# Critérios de aceitação
- [x] Postagem da gravação do treinamento
- [x] Postagem de um resumo do que foi desenvolvido no treinamento

**Comment by guibrbs** [comment]
## Treinamento de React, HTML e CSS
### Tópicos a serem abordados no treinamento:
- Como criar um projeto em React;
- Noções de HTML;
- Noções e conceitos de CSS;
- Componentes em React;
- Uso do Props entre componentes;
- Navegação com React.

**Comment by guibrbs** [comment]
## Comandos básicos para iniciar com um projeto em ReactJs no Linux
Instala o NodeJs, necessário para a criação e execução do projeto:
```
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - 
sudo apt-get install -y nodejs 
```
Cria um projeto e inicializa (atenção ao "nome-que-quiser", nessa parte coloque o nome da pasta que queira alocar o projeto):
```
npx create-react-app nome-que-quiser
cd nome-que-quiser
npm start --- (inicia o projeto no localhost)
```

**Comment by guibrbs** [comment]
## HTML
Elementos básicos:
`<head>` : Geralmente utilizado em conjunto com o título;
`<title>` :  Define o título do documento;
`<body>` : Conteúdo do documento;
`<header>` : Cabeçalho do documento;
`<footer>` : Rodapé do documento;
`<section>` : Representa uma seção do documento;
`<p>` : Parágrafo;
`<div>` : Usado para agrupar elementos em conteúdo de fluxo;
`<span>` : Também é usado para agrupar elementos, mas em conteúdo fraseado; 
`<img>` : Inserção de imagem;
`<nav>` : Seção com links de navegação;
`<ul>` : Lista de itens sem ordem;
`<ol>` : Lista de itens ordenados;
`<li>` : Item que faz parte de uma lista;

**Comment by guibrbs** [comment]
O treinamento de React foi realizado no dia 25/02/2022 via discord, abordando os seguintes temas:

> ## Treinamento de React, HTML e CSS
> ### Tópicos a serem abordados no treinamento:
> * Como criar um projeto em React;
> * Noções de HTML;
> * Noções e conceitos de CSS;
> * Componentes em React;
> * Uso do Props entre componentes;
> * Navegação com React.

### [Link para o treinamento](https://unbbr-my.sharepoint.com/:v:/g/personal/200037994_aluno_unb_br/EX-4s-z1029CqtRCSUNUQzEBrWxZuP2opWC0XQrljNAa9Q?e=9kp1Xa)

### Links usados durante o treinamento e links úteis para o desenvolvimento do assunto:
- [React Router Dom (Navegação em React)](https://github.com/remix-run/react-router/blob/main/docs/getting-started/tutorial.md)
- [UseState e UseEffect (citado no treinamento)](https://www.youtube.com/watch?v=6WB16wZS61c&ab_channel=Rocketseat)
- [Componentes e Props](https://pt-br.reactjs.org/docs/components-and-props.html)
- [Iniciando em React](https://www.youtube.com/watch?v=pDbcC-xSat4&ab_channel=Rocketseat) (Vídeo bom e atual)
