### ISSUE TITLE
Configuração do ambiente de trabalho

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#36]
# Descrição
Realizar a configuração do ambiente de trabalho geral, para que, durante a execução do projeto, todos os membros do time estejam com seus respectivos ambientes prontos para desenvolvimento.

# Tarefas
- [x] Definição dos versionamentos das ferramentas e linguagens de programação a serem utilizadas
- [x] Configuração do Docker

# Critérios de aceitação
- [x] Todos os membros participantes do projeto estarem com o ambiente de trabalho configurado corretamente

**Comment by RochaCarla** [comment]
falta descrição

**Comment by Matheuspleal** [comment]
# Pequeno projeto em python com contêinerização em docker
- dockerfile

```dockerfile
#Usando o python3.9
FROM python:3.9

#Adicione, a partir da pasta onde se encontra o dockerfile, o arquivo nome-do-arquivo.py ao contêiner
ADD teste.py /

#Rode o comando <comandos-aqui>
RUN pip install numpy

#No terminal de comando, faça: <comando1 comando2 ...>
CMD [ "python", "./teste.py" ]
```

```python
# Arquivo de teste da implementação do docker
import numpy as np

teste = np.log10(2)
print("log de 2 na base 10:", teste)
```
# Instruções para rodar este miniprojeto

1. Criar 2 arquivos em uma pasta, um com o nome dockerfile e outro com o nome teste.py
2. No terminal do linux, com o docker instalado rodar os seguintes comandos: 
```
docker build -t <nome-da-imagem> .
```
```
docker run <nome-da-imagem>
```

Com estes passos, você deverá obter o seguinte resultado em seu terminal:
```
log de 2 na base 10: 0.3010299956639812
```

**Comment by Matheuspleal** [comment]
## Links úteis para esta issue
. [Docker hub](https://hub.docker.com/)
. [Docmentação do Docker](https://docs.docker.com/)
. [Overview do Docker compose](https://docs.docker.com/compose/)

**Comment by Matheuspleal** [comment]
[Vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
[Aula rocketseat - criando um projeto react em 2022](https://www.youtube.com/watch?v=pDbcC-xSat4)

**Comment by Matheuspleal** [comment]
# Proposição de uso

Venho por meio desta propor o uso do Vite (com react) para a criação do projeto de front-end.

## Node

Com relação ao _[Node](https://nodejs.org/en/)_, que é a base para utilizarmos o _[react](https://pt-br.reactjs.org/)_, venho recomendar que utilizemos a versão 16.14.0, ou 16.x, que é a versão que possui LTS (long term support). Assim, sugiro que façamos a configuração do _node_ da seguinte forma

### Para Ubuntu

1. No terminal, utilizar os seguintes comandos:
   ```sh
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs
   ```
   - Assim, o node *em sua máquina* será sempre atualizado para a última versão LTS do node
2. Utilizar o comando:
    ```sh
    node --version
    ```
    - O resultado esperado (conforme a versão LTS atual) é:
    ```sh
    v16.14.0
    ```
## Vite

Com relação ao _[vite](https://vitejs.dev/)_, não é necessário a instalação de nenhum pacote. utilizaremos ele para realizar a criação de um projeto em react.ts, que utiliza _typescript_ ao invés de _javascript_.

Os passos a seguir para a criação do projeto vite + react são:

### Para ubuntu
1. No terminal, utilizar o comando de criaçao do projeto:
    ```sh
    npm create vite@latest <nome-do-projeto>
    ```
2. Assim, entraremos na seguinte janela, nela devemos selecionar a opção _*react*_:
    
    ![](https://i.ibb.co/2PxjRhD/Screenshot-from-2022-03-02-18-26-39.png)

3. E depois, selecionar _*react-ts*_ para um projeto em typescript:
   
    ![](https://i.ibb.co/WkmH7xy/Screenshot-from-2022-03-02-18-27-22.png)

4. Após a criação do projeto, usar os comandos:
    ```sh
    cd <nome-do-projeto>
    npm install
    npm run dev
    ```
5. E agora o seu projeto _react + vite_ estará pronto para ser visualizado em: http://localhost:3000

## Dockerizando o projeto

Agora, para realizar a dockerização do projeto, seguiremos os seguintes passos:

1. Criar um arquivo com o nome _dockerfile_ na pasta _/<nome-do-projeto>/_
   
    Nele, inserir:
    ```dockerfile
    FROM node:lts-alpine
    WORKDIR /app
    COPY package*.json /app/
    RUN npm install
    COPY . .
    EXPOSE 3000
    CMD ["npm", "run", "dev"]
    ```

2. Criar um arquivo com o nome _.dockerignore_ para agilizar o processo de montagem do contêiner:

    Nele, inserir:
    ```
    /node_modules
    npm-debug.log
    ```

3. Também devemos adicionar algumas linhas de código ao arquivo _vite.config.ts_:

    ```typescript
    import { defineConfig } from 'vite'
    import react from '@vitejs/plugin-react'

    // https://vitejs.dev/config/
    export default defineConfig({
        server: {
        host: '0.0.0.0',
        port: 3000,
        },
    plugins: [react()]
    })
    ```

    - Assim deve estar o arquivo após as alterações. Utilizaremos a tag _*server*_ para configurar o host e a porta que será utilizada.

4. Agora o projeto está pronto para ser dockerizado. Utilizaremos os seguintes comandos:

    ```sh
    docker build -t <nome-do-projeto> .
    docker run -dp 3000:3000 <nome-do-projeto> 
    ```

5. Com isso, o projeto dockerizado já estará em http://localhost:3000.

**Comment by Matheuspleal** [comment]
## Tecnologias escolhidas
Front-end:
- React

Back-end:
- Selenium WebDriver (Python)
- Django rest framework (Python)
- MongoDB

Ferramenta de BI:
- Metabase

**Comment by Matheuspleal** [comment]
Por fim, irei confeccionar um _**dockerfile**_ e um _**makefile**_ após a finalização do desenvolvimento inicial do front-end, que será a entrega mais visual da R1.

**Comment by Matheuspleal** [comment]
Por fim, irei confeccionar um _**dockerfile**_ e um _**makefile**_ após a finalização do desenvolvimento inicial do front-end, que será a entrega mais visual da R1. E com isso, todos que clonarem o repositório terão as versões corretas especificadas dentro dos arquivos citados.
