### ISSUE TITLE
Treinamento de Python

### ISSUE THREAD

**Issue by oCaioOliveira** [fga-eps-mds/2021.2-INDICAA#39]
# Descrição
Reunião dos grupos para treinamento das tecnologias específicas decididas pelo time.

# Tarefas
- [x] Treinamento Back-End (Python)

# Critérios de aceitação
- [x] Postagem da gravação do treinamento
- [x] Postagem de um resumo do que foi desenvolvido no treinamento

**Comment by oCaioOliveira** [comment]
O treinamento Python foi realizado no dia 25/02 e foi desenvolvido um código simples com a equipe sanando dúvidas dos participantes, a gravação será postada em breve, código a seguir: 

import operator as op

class Calculadora:
    gravidade =  9.8

    def init(self, x, y):
        self.x = x
        self.y = y

    def add(self, x, y):
        return x + y

    def sub(self, x, y):
        return x - y

    def mul(x, y):
        return x * y

    def div(x, y):
        return x / y

    def pow(x, y):
        return x ** y

    # numeros = [1, 2, 1, 3, 4, 5.0, "a", "oi"]
    # print(numeros[1:])
    # dict = {"nome": "Caio", "numero": 2}
    #
    # print("nome da pessoa = " + dict["nome"] + " oi")
    #
    # var = input("digite um numero\n")
    # print(var)
    #print(op.add(1, 2))

class Main:
    calculadora = Calculadora(5, 8)
    print(calculadora.add(2, 2))

Main()

#if x == 10 or y == 8:
#   ...
#elif x == 98 or y == 9:
#    ...
#else:

**Comment by Matheuspleal** [comment]
Solicito o fechamento desta issue, visto que o treinamento foi efetuado.

**Comment by oCaioOliveira** [comment]
Segue o link com a gravação da aula e o desenvolvimento do código supracitado:
https://unbbr-my.sharepoint.com/personal/200037994_aluno_unb_br/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F200037994%5Faluno%5Funb%5Fbr%2FDocuments%2FTreinamento%20de%20Python%2Emkv&parent=%2Fpersonal%2F200037994%5Faluno%5Funb%5Fbr%2FDocuments
