### ISSUE TITLE
Fazer issue templates

### ISSUE THREAD

**Issue by RochaCarla** [fga-eps-mds/2021.2-INDICAA#42]
# Descrição

As issues de vocês estão sem descrição, tarefas e critérios de aceitação. É uma péssima prática de comunicação e colaboração. O uso de template de issue facilita  documentar issues com melhor qualidade.

# Tarefas

- [ ] Estabelecer os tipos de issues do grupo (épico, feature, User Story, tarefa técnica, documentação, bug) 
- [ ] Fazer um template para caad tipo de issue

# Critério de aceitação

- [ ] Todos os templates estão disponíveis no repositório

**Comment by Matheuspleal** [comment]
A Issue #22 fez a criação de um issue template. Irei rever o template criado e porque ele não está como concluído no community standards

**Comment by Matheuspleal** [comment]
O issue template foi colocado na aba de community standards. Peço que o item seja revisado pelos criadores do issue template na issue #22.

**Comment by LeticiaAires** [comment]
O issue template, criado pelo @oCaioOliveira, foi revisado e atende às expectativas estabelecidas para o  item.

**Comment by Matheuspleal** [comment]
Só uma dúvida, vocês revisaram este issue template aqui ? https://github.com/fga-eps-mds/Projeto01/blob/main/.github/ISSUE_TEMPLATE/sprint--x-----tipo-da-issue-----o-que-ser--feito-.md

Esse foi o issue template que transferi pra poder contar pro community standards. Se houver algo que não está de acordo com o que vocês fizeram antes, favor corrigir! :D

**Comment by oCaioOliveira** [comment]
Revisamos sim @Matheuspleal :)

**Comment by Matheuspleal** [comment]
Agora o que resta é criar mais issue templates pra cada tipo de issue! Alocaremos isso pra essa semana ainda.

**Comment by Matheuspleal** [comment]
Ficarei responsável pelo template de issues relacionadas à bugs

**Comment by LeticiaAires** [comment]
@Matheuspleal procurei diferentes templates de issue do Aligabot e não encontrei.
Quais outras categorias precisam de serem criadas? Dessa forma, a gente divide entre nós.

**Comment by Matheuspleal** [comment]
Templates para criação de épicos e bugs pelo que eu consigo pensar agora

**Comment by LeticiaAires** [comment]
https://github.com/fga-eps-mds/2019.2-Acacia-Frontend/tree/develop/.github/ISSUE_TEMPLATE
O Acácia tinha um template de issues de reuniões. Vocês acham que convém fazer também?

**Comment by Matheuspleal** [comment]
Estou utilizando o template de doc de reunião(planning e review) que o @gabrielm2q me mandou por meio do meu grupo. Vou encaminhar via telegram

**Comment by Matheuspleal** [comment]
Adicionei um template de bug report, favor revisar.

**Comment by Matheuspleal** [comment]
Conforme falado em reunião, já temos templates que julgamos suficientes. portanto irei dar esta issue como fechada.
