### ISSUE TITLE
Criar Logo para o projeto

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/2021.2-INDICAA#45]
# Tarefas
- [x] Criar logo para o projeto em desenvolvimento
- [x] Substituir o logo temporário em https://github.com/fga-eps-mds/Projeto01/tree/main/docs/assets/img

# Critérios de aceitação
- [x] O logo deve estar em formato .png .jpeg ou .jpg
- [x] Logo no repositório

**Comment by Matheuspleal** [comment]
@guigudf @LeticiaAires Favor alocar +1 membro cada para esta issue.

**Comment by AdneMoretti** [comment]
Bom dia galera! Eu fiz um exemplo de logo, vou colocar aqui pra vocês opinarem e darem sugestões.

<img src="https://user-images.githubusercontent.com/64036847/154974979-89f07bd9-4946-4f84-b8d1-54e5f04783ea.jpg" width="200"/>

**Comment by AdneMoretti** [comment]
A logo foi criada e devidamente adicionada ao repositório do projeto.
