### ISSUE TITLE
Padronização de Branches

### ISSUE THREAD

**Issue by LeticiaAires** [fga-eps-mds/2021.2-INDICAA#50]
# Descrição
Configurar branches de acordo com o worflow definido

# Tarefas
- [x] Debater e definir workflow a ser seguido
- [x] Instaurar padrão para criação de branches

# Critérios de aceitação

- [x] Tópico deve ser discutido
- [x] Issue deve ser revisada e aprovada

**Comment by Matheuspleal** [comment]
O _grupo 3_ pode ficar responsável por esta issue ?

**Comment by lucasqueiroz23** [comment]
> O _grupo 3_ pode ficar responsável por esta issue ?

Por mim, tudo bem!

**Comment by Matheuspleal** [comment]
Nas políticas de contribuição do Acácia, consta uma política de criação de branches.

https://fga-eps-mds.github.io/2019.2-Acacia/#/policies

**Comment by Matheuspleal** [comment]
# Políticas de branch

## As branches criadas neste repositório devem seguir os padrões a seguir:

Uma breve explicação sobre o fluxo de trabalho:

- A branch _main_ representa uma versão estável do produto, contendo código já testado, versionado e revisado, pronto para ser entregue ao usuário final. Esta branch partirá através da branch _develop_ através de pull requests aprovados ao final de cada release.

Regras:

1. Existe apenas UMA branch _main_.
2. **Não** são permitidos commits feitos diretamente na branch _main_.

- A branch _develop_ contém a versão mais atualizada do código que está sendo desenvolvido. Esta branch está sempre sincronizada com a _main_ e é base para as branches _feature_.

Regras:

1. Existe apenas UMA branch _develop_.
2. Esta branch sempre é mesclada à branch _main_.

- As branches _feature_ representam as funcionalidades do sistema a serem desenvolvidas. Elas devem ter a branch _develop_ como sua origem e fim.

Regras de nomenclatura:

```
feature/(#Id-da-issue)-título-da-issue
```

- A branch _release_ representa o conjunto de funcionalidades provenientes de um ponto específico da branch _develop_. Esta branch contém funcionalidades prontas que, provavelmente, estarão presentes na próxima versão estável do produto. Apenas **bug fixes** são permitidos nesta branch.

Regras:

1. Esta branch é criada sempre a partir da branch _develop_.
2. Esta branch é mesclada às branches _develop_ e _master_.
3. Esta branch aceita apenas mesclagens de branches do tipo _bugfix_.


Regras de nomenclatura:

```
release/vNúmero-da-versão
```

- As branches do tipo _bugfix_ são utilizadas para implementar soluções para bugs, encontrados através de testes realizados em releases específicas, na branch _release_. Isso significa que a branch _bugfix_ deve ter a branch _release_ como sua origem e fim.

Regras:

1. Esta branch sempre é criada a partir da branch _release_.
2. Esta branch sempre é mesclada à branch _release_.

Regras de nomenclatura:

```
bugfix/(#Id-da-issue)-título-da-issue
```

- A branch _hotfix_ é utilizada para implementar soluções para problemas urgentes encontrados no ambiente de produção. Isso significa que esta branch deve ter a branch _main_ como sua origem e fim.

Regras:

1. Esta branch sempre é criada a partir da branch _main_.
2. Esta branch sempre é mesclada à branch _main_.

Regras de nomenclatura:

```
hotfix/(#Id-da-issue)-título-da-issue
```

**Comment by gabrielm2q** [comment]
O documento no [comentário acima](https://github.com/fga-eps-mds/2021.2-INDICAA/issues/50#issuecomment-1053558192) está pronto para ser revisado.

**Comment by joaopaulob3** [comment]
Só um comentário, pessoal: acredito que o documento elaborado devesse ser colocado no nosso docs. Além disso, é importante corrigir os links quebrados do [contributing](https://github.com/fga-eps-mds/2021.2-INDICAA/blob/main/docs/contributing.md) relativo à política de branchs e a política de commits.

**Comment by Matheuspleal** [comment]
O documento estará no docs do repositório assim que for revisado. E com relação aos links quebrados, iremos corrigir. Agora, gostaria de perguntar se você conseguiu revisar o documento acima pra nós.

**Comment by guigudf** [comment]
O documento foi revisado e está condizente com o git-flow utilizado como base.
Foi criado uma branch develop, como dito no documento, e solicito começarmos a trabalhar nela a partir da sprint 6

**Comment by Matheuspleal** [comment]
Obrigado pela revisão, @guigudf irei fechar a issue e upar o doc

**Comment by Matheuspleal** [comment]
O documento revisado se encontra [aqui](https://github.com/fga-eps-mds/2021.2-INDICAA/blob/main/docs/documentacao/guia_Branching.md).
