### ISSUE TITLE
Diagrama do projeto

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#53]
# Descrição
Criar um diagrama geral de pacotes para o projeto. [Vide 5.2 doc. de arquitetura do projeto acácia](https://fga-eps-mds.github.io/2019.2-Acacia/#/architecture_document).

# Tarefas

- [x] Levantamento dos elementos que serão inseridos no diagrama.
- [x] Criação do diagrama seguindo os padrões definidos nesta issue.

# Critérios de aceitação

- [x] O diagrama ter sido revisado.
- [x] O diagrama ter sido inserido no repositório do projeto dentro do [doc. de arquitetura](https://github.com/fga-eps-mds/Projeto01/blob/main/docs/documentacao/documento_de_arquitetura.md).

**Comment by guibrbs** [comment]
##  Diagrama de Pacotes 
### Versão 1
A versão 1 foi elaborada de acordo com a issue e o  diagrama de pacotes do projeto Acácia. Primordialmente foi feito um levantamento das tecnologias que serão utilizadas, tanto no Frontend quanto no Backend e posteriormente detalhamos os arquivos delas.

![Diagrama de Pacotes](https://user-images.githubusercontent.com/88190414/155862724-6e119d3c-9da5-43b2-99fd-2cbf34132daf.png)

**Comment by gabrielm2q** [comment]
# Referências
- Para o desenvolvimento do projeto, nos baseamos no [Diagrama de Pacotes do Projeto Acácia](https://fga-eps-mds.github.io/2019.2-Acacia/#/architecture_document), dando atenção especial à [Issue do Projeto Acácia](https://github.com/fga-eps-mds/2019.2-Acacia/issues/37) onde os integrantes do grupo comentam sobre o processo de desenvolvimento do diagrama (ver [comentário](https://github.com/fga-eps-mds/2019.2-Acacia/issues/37#issuecomment-533359416)).
- Além do Diagrama de Pacotes do Projeto Acácia, também prestamos atenção ao [Diagrama de Pacotes do Projeto CarDefense](https://fga-eps-mds.github.io/2018.2-CarDefense/docs/docarquitetura.html), que dá atenção ao Django Rest Framework.
- Com relação à arquitetura do Django Rest API, consultamos, para melhor entendimento, a seguinte fonte: [Django: POST, PUT, GET, DELETE requests example | Rest Apis](https://www.bezkoder.com/django-rest-api/)
- O Diagrama de Pacotes acima foi elaborado utilizando a plataforma LucidChart.
- Ver também: [O que é um Diagrama de Pacotes?](https://gitmind.com/pt/diagrama-de-pacotes.html#_2).

**Comment by guibrbs** [comment]
> o diagrama está de acordo com a ideia do projeto e pode ser inserido no [doc. de arquitetura](https://github.com/fga-eps-mds/Projeto01/blob/main/docs/documentacao/documento_de_arquitetura.md).

Diagrama de pacotes adicionado no documento de arquitetura, se for o caso @guigudf, favor inserir seu sobrenome para diferenciar os "Guilherme" no histórico de versões.

**Comment by oCaioOliveira** [comment]
Diagrama de Pacotes foi revisado e atende aos requisitos do projeto.
