### ISSUE TITLE
[BUG] - Bug no deploy do gitpages

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#56]
# **Descreva o bug**
O deploy do ambiente do gitpages está dando _faliure_.
 

# **Passo a passo para a reprodução do bug**
Para reproduzir o bug, siga os passos:
1. Vá até [a página inicial do repositótio](https://github.com/fga-eps-mds/2021.2-INDICAA).
2. Role a página para a seção de _enviroments_.
2. Clique em github-pages
4. Veja o bug

# **Comportamento esperado**
O comportamento esperado era que o status do deploy se apresentasse como _active_.

# **Contexto adicional**
O bug apareceu após a mudança do nome do repositório do projeto.

**Comment by Matheuspleal** [comment]
### Para corrigir o bug onde o gitpages do projeto apresentava _faliure_, tomei os seguintes passos:
1) Entrei na página de [_pages build and deployment_](https://github.com/fga-eps-mds/2021.2-INDICAA/runs/5298309140?check_suite_focus=true).
 2) Cliquei no link cujo nome é _deployed_ e que apresentava a tag _faliure_.
 3) Por fim, cliquei em _Re-run all jobs_ e com isso o erro foi corrigido.
 
Com isso, solicito a que algum membro faça a conferência da tag na [página principal do repositório](https://github.com/fga-eps-mds/2021.2-INDICAA) e confira se o status está atualizado para _active_.

**Comment by gabrielm2q** [comment]
No presente momento, o status está como "*active*" (vide imagem abaixo). Portanto, acredito que o bug foi corrigido!
![image](https://user-images.githubusercontent.com/72149063/155604620-8b50d43d-8b5a-4a1d-8879-fa8b5a4dc7fd.png)
