### ISSUE TITLE
Documento de Gerenciamento de Riscos 

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/2021.2-INDICAA#58]
# Descrição
Criar o documento de Gerenciamento de Riscos do projeto. [Vide Gerenciamento de Riscos do projeto N26](https://fga-eps-mds.github.io/2019.2-Over26/#/risk-manegement).

# Tarefas

- [x] Realizar levantamento de dados dos possíveis riscos que podem vir a acontecer durante o uso do programa.
- [x] Criação do documento seguindo os padrões definidos nesta issue.

# Critérios de aceitação

- [ ] O documento ter sido revisado.
- [x] O documento ter sido inserido no repositório do projeto dentro da pasta de [documentação](https://github.com/fga-eps-mds/Projeto01/blob/main/docs/documentacao).

**Comment by Matheuspleal** [comment]
PO's dos grupos serão os asignees

**Comment by AdneMoretti** [comment]
Após pesquisa, links que serão utilizados como base para o desenvolvimento do documento de gerenciamento de riscos do projeto:
- [Doc de gerenciamento-AlligaBot](https://fga-eps-mds.github.io/2021.1-AlligaBot/2021/08/09/plano-de-gerenciamento-de-riscos/) 
- BRASIL, Brasil; Ada - Plano de Gerenciamento de Riscos. Disponível em: https://fga-eps-mds.github.io/2019.1-ADA/#/docs/project/risk_management_plan 
- VILARINS, Augusto; FRANÇA, Emanoel; SOARES, Ingrid. GamesBI - Riscos. Disponível em: https://fga-eps-mds.github.io/2018.2-GamesBI/viabilidade/riscos.html

**Comment by AdneMoretti** [comment]
As últimas alterações do documento foram feitas e este já está na branch develop, aguardando revisão.

**Comment by Matheuspleal** [comment]
A revisão foi feita e o PR #78 foi aceito, logo a issue está finalizada.
