### ISSUE TITLE
Documento de Metodologia 

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/2021.2-INDICAA#60]
# Descrição
Criar o documento de Metodologia do projeto. [Vide Metodologia do projeto N26](https://fga-eps-mds.github.io/2021.2-INDICAA/#/metodology/metodology-plan).

# Tarefas

- [x] Exemplificar as funções dos membros dos grupos.
- [x] Descrever como se dará o planejamento e reuniões dos times.
- [x] Criação do documento seguindo os padrões definidos nesta issue.

# Critérios de aceitação

- [x] O documento ter sido revisado.
- [x] O documento ter sido inserido no repositório do projeto dentro da pasta de [documentação](https://github.com/fga-eps-mds/Projeto01/blob/main/docs/documentacao).

**Comment by joaopaulob3** [comment]
Peço que revisem o documento, em especial, o tópico 4. Verifiquem se há a necessidade de deixar alguns tópicos no documento como o XP por exemplo.

**Comment by MorettiGS** [comment]
@joaopaulob3 O documento ainda não está pronto. Foram divididas, em reunião, as tarefas de preencher e alterar o documento entre @MorettiGS, @gabrielm2q e @Mateusvff, e ainda iremos adicionar as devidas alterações. O documento que se encontrava no repositório anteriormente era apenas uma pequena estrutura adaptada do [documento de referência do Acacia](https://github.com/fga-eps-mds/2019.2-Acacia/blob/develop/docs/project_methodology.md), ainda incompleta.

**Comment by gabrielm2q** [comment]
Acabei de inserir a introdução das metodologias (introdução do tópico 2), a apresentação da "estrutura das sprints" (tópico 2.1.3), o extreme programming (tópico 2.3) e o resumo da interação entre membros e treinamentos (tópico 4)
As referências utilizadas durante a pesquisa foram adicionadas e a tabela de versões consta como foram feitos pequenos "patches" no documento.

Os tópicos citados (exclusivamente) podem ser revisados (agora ou ao final da produção do documento).

**Comment by MorettiGS** [comment]
Foram inseridas as descrições de introdução ao documento, tópico 1, e ao Scrum, tópico 2.1, assim como também foram feitas as devidas alterações à descrição do Timebox, tópico 2.1.4, para melhor englobar o projeto do INDICAA.
Com essas mudanças, também foi atualizada a tabela de versões e as referências utilizadas.

Portanto, tais tópicos podem ser revisados.

**Comment by Mateusvff** [comment]
Foram inseridas as descrições do Product Backlog, das principais funções relacionadas à metodologia Scrum, como utilizaremos os quadros de visualização do Kanban em nosso projeto e do plano de comunicação da equipe.

**Comment by gabrielm2q** [comment]
Documento pronto e disponível para revisão!

**Comment by joaopaulob3** [comment]
Documento revisado atendendo às especificações exigidas pela issue. Como dito, usamos o documento do Acácia como referência. Acredito que a issue já possa ser fechada @guigudf.
