### ISSUE TITLE
Gerar a release R1

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#62]
# Tarefas
- [x] Realizar a conferência dos arquivos que serão incluídos na _**Release R1**_.
- [x] Criação das _**release notes**_ em _markdown_.

# Critérios de aceitação
- [x] _**Release notes**_ terem sido revisadas e criadas corretamente.
- [x] Todos os documentos produzidos pela equipe terem sido incluídos nas _**Release notes**_.
- [x] Geração da release.

**Comment by guigudf** [comment]
favor fechar a issue

**Comment by Matheuspleal** [comment]
Releases geradas:

[Front-end](https://github.com/fga-eps-mds/2021.2-INDICAA-Front-end/releases/tag/v0.1)
[Wiki - Docs](https://github.com/fga-eps-mds/2021.2-INDICAA/releases/tag/v0.1)
