### ISSUE TITLE
Desenvolvimento inicial do Front-end

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#66]
# Tarefas
- [x] Desenvolver o início do Front-end do projeto.
- [x] Dockerizar a aplicação.
- [ ] Criar o _**makefile**_.

# Critérios de aceitação
- [x] As versões das tecnologias definidas na issue #36 devem ser respeitadas.
- [x] O Front-end deve passar por testes de funcionamento em diferentes máquinas.
- [x] O processo para a execução do projeto deve ser descrita no _**README.md**_ do repositório.

**Comment by Matheuspleal** [comment]
Esta issue está ligada diteramente ao [repositório do front-end do projeto](https://github.com/fga-eps-mds/2021.2-INDICAA-Front-end).

**Comment by guibrbs** [comment]
Foi feito um commit inicial do Front-end, nele a equipe de MDS conseguiu desenvolver a tela inicial proposta pelo [Protótipo de Alta Fidelidade](https://github.com/fga-eps-mds/2021.2-INDICAA/issues/34#issuecomment-1058527589). Nesse desenvolvimento inclui a adição da logo e o nome do projeto, uma barra de pesquisa com os ícones e botões e as seleções dos campus da Universidade de Brasília, incluindo efeitos ao clique.

**Comment by MorettiGS** [comment]
Foi feito mais um commit ao Front-end do projeto. como proposto no Protótipo de Alta Fidelidade previamente citado. Dessa vez, o commit envolve a adição dos elementos do [React Router](https://reactrouter.com/) à página ( compondo as rotas predeterminadas do projeto ) e também algumas alterações nos arquivos CSS e nomes de componentes React, com o objetivo de melhorar o visual e o código da página.

**Comment by guibrbs** [comment]
Foi feito mais um commit alterando a estilização dos filtros e adicionando na página de detalhes, e a localização em relação ao container.

**Comment by guibrbs** [comment]
Foi adicionado ao site o link para o repositório do projeto, bem como a funcionalidade de passar o mouse por cima do "i" e mostrar a ajuda ao usuário. Além de na página de Resultados, ser adicionado junto com o filtro, uma imagem ilustrativa dos gráficos que serão obtidos com a ferramenta "metabase". E por fim, na página de Detalhes, foi adicionado, juntamente com o filtro, uma imagem ilustrativa dos detalhes que aparecerão de acordo com a pesquisa do usuário.

**Comment by gabrielm2q** [comment]
Foi realizada a conteinerização do atual projeto.

**Comment by Matheuspleal** [comment]
```sh
docker build -t 2021-2_indicaa_front-end .
docker run -dp 3000:3000 2021-2_indicaa_front-end
```

**Comment by gabrielm2q** [comment]
As instruções foram adicionadas ao [Repositório do Front-End](https://github.com/fga-eps-mds/2021.2-INDICAA-Front-end). O pull request da branch "develop" para a "main" foi realizado.

**Comment by gabrielm2q** [comment]
O makefile será feito para a release 2.
