### ISSUE TITLE
Criar guia de estilo do projeto.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#70]
# Descrição
Criação de uma documentação que servirá de guia de identidade visual para o front-end.

# Tarefas
- [x] Definir paleta de cores.
- [x] Discussão sobre logo.
- [x] Definição das fontes de letra.
- [x] Definição dos conjuntos e padrões de ícones.

# Critérios de aceitação
- [x] O guia de estilo visual deve estar no repositório e no git pages.
- [x] O guia de estilo visual deve ser de fácil entendimento.
- [x] O guia de estilo visual deve ser revisado.

**Comment by LeticiaAires** [comment]
Boa tarde, gente! Quando podemos nos reunir para discutir o tema?

**Comment by AdneMoretti** [comment]
> Boa tarde, gente! Quando podemos nos reunir para discutir o tema?

Boa tarde! Quando fica bom pra vocês?

**Comment by Mateusvff** [comment]
Bom dia! Hoje eu consigo a partir das 19h, se puderem esse horário, seria ótimo.

**Comment by LeticiaAires** [comment]
Por mim pode ser 19h também

**Comment by vitorekr** [comment]
estou disponivel

**Comment by LeticiaAires** [comment]
http://www.marca.unb.br/arquivosdigitais/files/guia_pratico/guia_pratico.pdf

**Comment by Mateusvff** [comment]
@AdneMoretti @mc-gomes @LeticiaAires @vitorekr Pelo que vi em outras documentações, não encontrei em nenhuma a parte de padrões de ícones, acham que é necessário colocar?

**Comment by vitorekr** [comment]
Acredito que seja um extra bacana. Mas não que seja necessário colocar.

**Comment by Matheuspleal** [comment]
Upei a paleta de cores, porém o que falta é a parte que fala de contraste... Será se alguém pode completar essa parte para fecharmos essa issue ?

**Comment by LeticiaAires** [comment]
Paleta de cores terminada.
Por favor revisem o documento para já fecharmos a issue.

**Comment by Matheuspleal** [comment]
o PR #91 foi criado, a issue segue para revisão.

**Comment by Matheuspleal** [comment]
Com o merge do PR #91 Esta issue está concluída
