### ISSUE TITLE
Reestilização visual do projeto.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#72]
# Descrição
Reestilizar o projeto no figma, para criar um software mais visualmente agradável e moderno.

# Tarefas
- [x] Buscar inspirações em sites modernos.
- [x] Criar a página principal.
- [x] Pedir opinião externa.

# Critérios de aceitação
- [x] O projeto figma deve estar visível pata todos.
- [x] O projeto deve seguir o guia de estilo visual criado na issue #70 .
- [x] O projeto deve estar visualmente moderno e agradável.

**Comment by Matheuspleal** [comment]
## Inspirações

https://dribbble.com/shots/17686194-Lesson-Plan-Home-Page-Comp
https://dribbble.com/shots/17680264-Education-Web-Design-Landing
https://dribbble.com/shots/17687127-Team-management-Dashboard
https://dribbble.com/shots/17171783-Project-Management-Dashboard-UI-Concept
https://dribbble.com/shots/15725741-Sales-Dashboard

**Comment by Eruel6** [comment]
## Inspirações 

https://dribbble.com/shots/16935751-Schoolvoice-sidebars
https://dribbble.com/shots/15665480-The-Teamsy-dashboard-design
https://dribbble.com/shots/17576226-Boostboard-Dashboard-Design
https://dribbble.com/shots/17257234-Gig-Share-Dashboard
https://dribbble.com/shots/17136158-Fashionhub-Member-Offer-Reports-Dashboard

**Comment by guibrbs** [comment]
## Inspirações
https://dribbble.com/shots/15182870-Educame-Web-App
https://dribbble.com/shots/17689079-Loyal-Business-Webapp
https://dribbble.com/shots/17690624-E-Commerce-Dashboard-Panel
https://dribbble.com/shots/15544660-Choies-App-is-an-online-food-ordering-Reports-screen
https://dribbble.com/shots/17667342-DailyUI-22-Search
https://dribbble.com/shots/15369006-HuntJobs-Job-Search-Dashboard

**Comment by Matheuspleal** [comment]
## Protótipos feitos

- https://www.figma.com/file/jwle1wmYYdsTGcWYgGO24S/Front-end-INDICAA?node-id=0%3A1

**Comment by Matheuspleal** [comment]
Os protótipos estão em sincronia com o guia de estilo visual proposto em: #70. Caso o PR #91 seja aceito, nenhuma mudança é necessária.
