### ISSUE TITLE
Feedback pessoal da Release 01

### ISSUE THREAD

**Issue by lucasqueiroz23** [fga-eps-mds/2021.2-INDICAA#73]
# Descrição
Dar feedback individual da release 1 para a professora.

# Tarefas
- [x] Cada membro deve ler o email da professora
- [x] Cada membro deve escrever um email que abranja todos os tópicos requisitados pela professora

# Critérios de aceitação
- [x] Todos os membros do grupo devem enviar o feedback para a professora
- [x] Todos os membros do grupo devem avisar, nos comentários dessa issue, que enviaram o feedback para a professora

**Comment by LeticiaAires** [comment]
Boa tarde! Feedback enviado, professora.

**Comment by mc-gomes** [comment]
Feedback enviado ✌🏽

**Comment by laurapinos** [comment]
Feedback enviado!

**Comment by vitorekr** [comment]
Feedback enviado!
