### ISSUE TITLE
Atualizar o escopo nos documentos.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#74]
# Descrição
Realizar as mudanças necessárias no escopo do projeto com base no novo entendimento obtido.

# Tarefas
- [x] Revisar o escopo no _**[termo de abertura do projeto](https://github.com/fga-eps-mds/2021.2-INDICAA/blob/main/docs/documentacao/termo_de_abertura.md)**_
- [x] Revisar o escopo no _**[documento de arquitetura](https://github.com/fga-eps-mds/2021.2-INDICAA/blob/main/docs/documentacao/documento_de_arquitetura.md)**_
- [x] Revisar o escopo no _**[documento de visão](https://github.com/fga-eps-mds/2021.2-INDICAA/blob/main/docs/documentacao/documento_de_visao.md)**_
- [x] Realizar as mudanças nos documentos necessários.

# Critérios de aceitação
- [ ] O escopo deve ter sido atualizado, ou revisado, nos documentos citados acima.

**Comment by MorettiGS** [comment]
Foram revisados os três documentos em questão, e, junto às correções de alguns pequenos erros encontrados nos documentos, foram feitas as alterações necessárias no documento de arquitetura e no termo de abertura, respectivamente.

Com isso, as devidas revisões já podem ser efetuadas acima de todos esses documentos.

**Comment by Matheuspleal** [comment]
As mudanças feitas estão de acordo com o propósito do projeto e o escopo agora está mais claro e explicativo.
