### ISSUE TITLE
Atualização do fluxograma da política de branching

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#75]
# Descrição
O fluxograma da política de branching criada está incorreto, portanto, o fluxograma deverá ser corrigido e atualizado no repositório

# Tarefas
- [x] Corrigir fluxograma segundo a política de branching.

# Critérios de aceitação
- [x] O fluxograma deverá ser revisado.
- [x] O fluxograma deverá estar de acordo com o git flow.

**Comment by MorettiGS** [comment]
As mudanças desejadas foram realizadas e a pull request relativa à issue, com o fluxograma, encontra-se para revisão.

**Comment by Matheuspleal** [comment]
O PR #79 foi aceito, portanto a issue foi completada.
