### ISSUE TITLE
Sincronização da branch develop.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#76]
# Descrição
A branch _**develop**_ está desatualizada com relação à main. Portanto, devemos atualizá-la e começar a utilizar a política de branches que foi atualizada na issue #75.  

# Tarefas
- [x] Criar pull request para deixar a branch develop em sincronia com a main

# Critérios de aceitação
- [x] Pull request deve ter sido criado e descrito de forma clara e sucinta
- [x] Pull request deve ter sido aceito por outro membro (Sem ser o que criou o PR)

**Comment by MorettiGS** [comment]
Foi realizada a criação do _pull request_ (#77) que cumprirá o objetivo desta issue.

O mesmo se encontra livre para revisão, e peço que ela seja feita considerando os critérios de aceitação desta issue e a checklist existente no comentário do próprio PR.

**Comment by Matheuspleal** [comment]
@everyone Agora que a branch develop está atualizada, devemos utilizar o padrão de branching do git flow, que é o mesmo que será descrito pelo fluxograma da issue #75. **NÃO** serão mais permitidos commits diretamente na branch main.
