### ISSUE TITLE
Metabase

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#81]
# Descrição

Utilizaremos o [Metabase](https://www.metabase.com/start/oss/) como ferramenta de BI para a mostragem dos dados coletados via web scraping da lista de ofertas do [SIGAA](https://sig.unb.br/sigaa/public/turmas/listar.jsf?aba=p-ensino). Aqui neste épico, agruparemos todas as issues relacionadas para o melhor controle da equipe.

# Issues
- Issue #87

**Comment by Matheuspimentell** [comment]
Metabase funcionando corretamente em ambiente local
