### ISSUE TITLE
Mapear dados de vagas disponíveis

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#83]
# Descrição
Nesta issue serão mapeados e documentados os dados a serem lidos, relacionados às vagas disponíveis, para facilitar o tratamento de dados e o web scraping.

# Tarefas
- [x] Criar uma documentação para receber os dados analisados (Em markdown ou em forma de tabela).
- [x] Analisar os dados de quantidade de vagas disponíveis na lista de oferta do SIGAA.
- [x] Estabelecer padrões observados.
- [x] Preencher a documentação criada com os padrões observados.

# Critérios de aceitação
- [ ] Tabela criada e acessível à todos (em forma de link).
- [ ] Revisão dos padrões observados.

**Comment by MorettiGS** [comment]
O valor da quantidade de vagas disponíveis pode ser encontrado com base no link: https://sig.unb.br/sigaa/public/turmas/listar.jsf, após selecionar o nível de ensino, unidade e o semestre desejado.

Como os dados apresentados apenas envolvem a quantidade de vagas ofertadas e a quantidade de alunos matriculados, a quantidade de vagas disponíveis deve ser calculada pela **diferença** entre essas duas.

Visualmente, os dados de quantidade de vagas ofertadas e o de quantidade de alunos matriculados encontram-se na quinta e sexta coluna da tabela, respectivamente.
Dentro do código, visto que existe um < td > a mais, os dados se encontram uma coluna à frente, ficando na sexta e sétima colunas.

O método de mapeamento das variáveis seguem o seguinte modelo, por xpath:

```
#Vagas ofertadas:
driver.find_element_by_xpath('//*[@id="turmasAbertas"]/table/tbody/tr[X]/td[6]')

#Alunos matriculados:
driver.find_element_by_xpath('//*[@id="turmasAbertas"]/table/tbody/tr[X]/td[7]')
```

Onde o X em "tr[X]" representa o número da linha desejada (obs: também contamos a linha que tem o código e nome da disciplina).

Porém, também seria possível encontrar os dados de forma mais simples, visto que as ocorrências de "style='text-align: center;'" ocorrem apenas para esses dois dados, assim utilizando:

```
driver.find_elements_by_xpath('//*[@id="turmasAbertas"] and [@style="text-align: center"])
```

Retornando assim valores como:
qtde de vagas para a linha 1, qtde de alunos matriculados para a linha 1, qtde de vagas para a linha 2, etc...

## Colaboradores
@MorettiGS

**Comment by Matheuspleal** [comment]
O mapeamento dos dados foi feito de forma correta e a descrição está bem explicativa.
