### ISSUE TITLE
Mapear dados de quantidade de alunos matriculados

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#84]
# Descrição
Nesta issue serão mapeados e documentados os dados a serem lidos, relacionados à quantidade de alunos matriculados, para facilitar o tratamento de dados e o web scraping.

# Tarefas
- [x] Criar uma documentação para receber os dados analisados (Em markdown ou em forma de tabela).
- [x] Analisar os dados de quantidade de alunos matriculados na lista de oferta do SIGAA.
- [x] Estabelecer padrões observados.
- [x] Preencher a documentação criada com os padrões observados.

# Critérios de aceitação
- [x] Tabela criada e acessível à todos (em forma de link).
- [x] Revisão dos padrões observados.

**Comment by guigudf** [comment]
O valor da quantidade de alunos matriculados se encontra no link: https://sig.unb.br/sigaa/public/turmas/listar.jsf, após selecionar o nível de ensino, unidade e o semestre desejado.
Ele é apresentado na sexta coluna, sobre o nome de "Qtde Vagas Ocupadas".

O método de mapeamento da variável segue o seguinte modelo:

```
driver.find_element_by_xpath('//*[@id="turmasAbertas"]/table/tbody/tr[X]/td[7]
```
Onde o X em "tr[X]" representa o número da linha desejada (obs: também contamos a linha que tem o código e nome da disciplina)

## Colaboradores
@guigudf

**Comment by guigudf** [comment]
Foi verificado que as ocorrências de "style='text-align: center;'" ocorrem apenas para a quantidade de vagas e alunos matriculados, então talvez possamos usar 

```
driver.find_elements_by_xpath('//*[@id="turmasAbertas"] and [@style='text-align: center'])
```
para separar melhor os dados, pois retorna todos os valores encontrados na ordem de ocorrencia, algo como:
qtde de vagas para a linha 1, qtde de alunos matriculados para a linha 1, qtde de vagas para a linha 2, etc...

**Comment by guibrbs** [comment]
Foi feita a revisão dos padrões observados.
Somente atentar ao "finders" do Selenium, no caso foi utilizado o "find_element_by...", uma vez que esse modo de uso está obsoleto (deprecated), então será feito o uso do "find_element(By...).
Com relação aos demais tópicos está tudo certo!
