### ISSUE TITLE
Mapear dados de salas "disponíveis"

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#85]
# Descrição
Nesta issue serão mapeados e documentados os dados a serem lidos, relacionados às salas, para facilitar o tratamento de dados e o web scraping.

# Tarefas
- [x] Criar uma documentação para receber os dados analisados (Em markdown ou em forma de tabela).
~- [ ] Analisar os dados de salas na lista de oferta do SIGAA.~
~- [ ] Estabelecer padrões observados.~
- [x] Preencher a documentação criada com os padrões observados.

# Critérios de aceitação
- [x] Comentários com os padrões observados no SIGAA.
- [x] Revisão dos padrões observados.

**Comment by Matheuspleal** [comment]
## Dados de local, de forma geral são dispostos desta forma
remoto
presencial
a definir
a designar

## Porém, algumas inconsistências foram encontradas nos seguintes departamentos:

quando houver _**???**_ significa que é um dado não identificado no momento

---
### Depto. de farmácia
   - <Nome do prédio>
   - <Nome do prédio> <Bloco> <Sala>
---
### Depto. de matemática 
   - ??? MAT ASS n°, MAT ASS n°
---
### Depto. de sociologia 
   - Aguardando alocação de sala
---
### Depto. administração 
   - < Nome do campus >
---
### Depto. economia
   - (<Nome do prédio> <Bloco> <Sala>)
---
### Depto. engenharia civil e ambiental
   - Presencial - Sala a designar
   - Presencial - <prédio> <Sala>
   - Presencial - <Local>
   - Presencial - <Local> <Prédio>
---
### Depto. engenharia florestal 
   - <Nome do prédio> <sala> <???>
   - <Nome do prédio> <sala> <pavimento>
   - <Nome do prédio <dia da semana> <sala> - <dia da semana <sala> <pavimento>
---
### Depto. linguas estrangeiras e tradução
   - remoto/presencial (seria semipresencial ?)
---
### Depto. música 
   - <Nome do prédio> <sala> <cidade ?>
---
### Depto. nutrição 
   - <Local: Hospital universitário, Pomed CMB DF, etc>
---
### Faculdade de medicina
   - <local: laboratório>
   - <sala, sala?, sala?>
---
### instituto de ciencias humanas
   - MULTIPOLO?
   - <cidade: POSSE - GO>
---
### Instituto de geociencias 
   - Obs/Sis ???
   - <sala>
   - <local: observatório sismológico>
---

**Comment by PedroSiq** [comment]
Para os demais departamentos analisados, não foram identificadas anomalias em relação ao padrão estabelecido pelo dicionário de dados (em #106) e previamente por esta issue. Caso não haja objeção, a issue pode ser fechada.
