### ISSUE TITLE
Download e teste do Metabase open source edition.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#87]
# Descrição
O Metabase possui uma versão gratuita e open source, esta issue se dedicará aos testes e compreensão sobre o uso desta versão do metabase.

# Tarefas
- [x] Download da _docker image_ do Metabase pelo _**Docker hub**_.
- [x] Mostrar dados "dummy" no Metabase open source, em localhost.
- [x] Criação de um "tutorial" para a utilização desta versão do Metabase.
- [x] Postagem de capturas de tela para mostrar os dados exibidos.

# Critérios de aceitação
- ~[ ] O Metabase deve estar funcionando corretamente em localhost.~
- ~[ ] Os arquivos necessários devem ter sido commitados adequadamente no [repositório do front-end](link).~
- [x] As capturas de tela devem estar em formato de comentários nesta issue, com suas respectivas descrições.

**Comment by guibrbs** [comment]
## Tutorial Metabase
Primeiramente é importante ter em mãos o docker e como executar ele, pois a partir dessa aplicação, iremos rodar a imagem do Metabase.
```
Dentro do terminal linux, com o docker já configurado, rode:

docker run -d -p 3000:3000 --name metabase metabase/metabase
```
Tecle enter. Após isso, o Metabase já estará rodando no localhost:3000.

- Dentro do localhost, aparecerá uma tela de setup, aparecendo a opção de escolher o idioma:

![Sem título](https://user-images.githubusercontent.com/88190414/159488107-15db2cb2-c675-4989-bafc-6741a0cb248f.png)
- Posteriormente, é necessário a criação de uma conta no Metabase:

![image](https://user-images.githubusercontent.com/88190414/159488387-3d954dc7-56e7-44f6-b6d5-fa46d45399e2.png)

- No próximo passo, é requisitado a adição de banco de dados, mas como não temos ainda, podemos clicar em "Vou adicionar meus dados depois":

![image](https://user-images.githubusercontent.com/88190414/159489225-0638c51e-7aee-4ae4-945a-508fa7aafd0f.png)

- O último passo da configuração inicial do metabase é pessoal, então cabe ao usuário decidir: 

![image](https://user-images.githubusercontent.com/88190414/159489562-329f5158-cc35-4642-8dbc-1e7cff33f9d6.png)

**Comment by guibrbs** [comment]
Como não temos um banco de dados estruturado e populado, o Metabase oferece um sample database, e a partir dele podemos verificar alguns gráficos.
Como por exemplo, dentro dessa database encontra-se a table "People", populada da seguinte forma (como a database é grande, serão mostrados somente os 20 primeiros IDs):

![image](https://user-images.githubusercontent.com/88190414/159490819-a908084f-108d-4435-be13-97f6e3ab7aa8.png)

- A partir dessa table, podemos visualizar dashboards com as informações concedidas, como por exemplo um Overview geral: 

![image](https://user-images.githubusercontent.com/88190414/159491462-178438b3-c6d0-4195-bf7b-c76b1b370004.png)

- Ou até mesmo a localização das pessoas por coordenadas ou por estado: 

![image](https://user-images.githubusercontent.com/88190414/159491684-cefd29c8-2d07-4741-aec3-644fe2b2192f.png)

- E por fim, o último dashboard criado por padrão do Metabase se trata de como essas pessoas estão distribuídas, seja por cidade ou por fonte: 

![image](https://user-images.githubusercontent.com/88190414/159492617-2bb70392-f5ef-4428-b110-794ef253c400.png)

Com isso conclui-se que com um banco de dados bem populado e organizado, é possível mostrar qualquer informação que tenha conexão de forma simples e elegante, uma vez que é disponibilizado o gráfico automaticamente.

**Comment by guibrbs** [comment]
Com o questionamento de como seria disponibilizado o acesso ao público alvo do projeto, a equipe do INDICAA foi atrás de como fazer o deploy da aplicação em algum lugar. 
Encontramos que é possível subir a aplicação no [Heroku](https://www.heroku.com/) e que o próprio Metabase facilita a configuração e a hospedagem ([Running Metabase on Heroku](https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-heroku.html)).
Com isso, subimos uma aplicação teste e verificamos que além do Metabase estar ao ar para qualquer usuário, os admins conseguem colaborar juntos, então utilizaremos o Heroku para servir ao usuário final nossos dashboards e para a colaboração entre a equipe. 
[Link para o deploy teste no Heroku](https://indicaa.herokuapp.com)

**Comment by Matheuspleal** [comment]
Com o deploy, a issue está finalizada!
