### ISSUE TITLE
Web scraping dos dados de quantidade de alunos matriculados.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#92]
# Descrição
Esta issue se dedicará ao scraping dos dados de quantidade de alunos matriculados, para popular o banco de dados que será gerado. Obs.: Nesta issue, o scraping se dedicará somente aos dados do departamento: **FACULDADE DO GAMA - BRASÍLIA**.

# Tarefas
- [x] Contar quantos alunos matriculados existem no geral.
- [x] Contar quantos alunos matriculados, por disciplina, existem.
- [x] Contar quantos alunos matriculados, por turma, existem.
- [x] Imprimir os dados no terminal.

# Critérios de aceitação
- [x] A quantidade de alunos matriculados contada (Geral, por disciplina e por turma) deve ser igual à quantidade contada no **SIGAA*.
- [x] Os dados devem ser impressos no terminal após a execução do scraping.
- [x] O código deve ser revisado.

**Comment by AdneMoretti** [comment]
O código do web scraping de alunos matriculados na Faculdade do Gama foi realizado, neste, são obtidos os seguintes dados:
- Quantidade de alunos matriculados por turma;
- Quantidade de alunos matriculados por materia;
- Quantidade de alunos matriculados em todas as turmas do departemanto
Durante a execução do código, os dados foram armazenados em duas listas de dicts, uma contendo as turmas e as suas informações e outra contendo as matérias e as informações, ao final, esses dicts são impressos no terminal.
O código foi realizado em conjunto com @MorettiGS @LeticiaAires e @guigudf

**Comment by gabrielm2q** [comment]
# Revisão
O código funciona normalmente e retorna a saída esperada.
