### ISSUE TITLE
Web scraping dos dados de quantidade de vagas disponíveis.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#93]
# Descrição
Esta issue se dedicará ao scraping dos dados de quantidade de vagas disponíveis, para popular o banco de dados que será gerado. Obs.: Nesta issue, o scraping se dedicará somente aos dados do departamento: **FACULDADE DO GAMA - BRASÍLIA**.

# Tarefas
- [x] Contar a quantidade de vagas disponíveis que existem no geral.
- [ ] Contar a quantidade de vagas disponíveis, por disciplina, que existem.
- [x] Contar a quantidade de vagas disponíveis, por turma, que existem.
- [x] Imprimir os dados no terminal.

# Critérios de aceitação
- [x] A quantidade de vagas disponíveis contada (Geral, por disciplina e por turma) deve ser igual à quantidade contada no **SIGAA*.
- [x] Os dados devem ser impressos no terminal após a execução do scraping.
- [ ] O código deve ser revisado.

**Comment by gabrielm2q** [comment]
Nos reunimos (@guibrbs) para comentar e fazer breves alterações no código de scraping desenvolvido pelo @guigudf.
O código cumpre alguns dos requisitos da issue, mas ainda é necessário  "Contar a quantidade de vagas disponíveis que existem no geral" e "Contar a quantidade de vagas disponíveis, por disciplina, que existem".
Aguardamos o posicionamento do @guigudf para subir o código para uma branch específica da feature.

**Comment by guibrbs** [comment]
Código desenvolvido pelo @guigudf (com os comentários e breves alterações):
```
import time
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options
from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.common.keys import Keys

# Configuração do Navegador (Firefox)
option = Options()
option.headless = True
driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())

# Acessar a página inicial da Consulta de Turmas do SIGAA
def acessarURL():
    url = "https://sig.unb.br/sigaa/public/turmas/listar.jsf?aba=p-ensino"
    driver.get(url)

# Selecionando a opção da "Graduação"
def selecionarNivelEnsino():
    botaoCampoEnsino = driver.find_element(By.ID, 'formTurma:inputNivel')
    botaoGraduacao = driver.find_element(By.XPATH,
                                         '//*[@id="formTurma:inputNivel"]/option[3]')
    botaoCampoEnsino.click()
    botaoGraduacao.click()

# Função que pode ser usada para selecionar um semestre específico
# def selecionarSemestre():
#     inputAno = driver.find_element(By.ID, "formTurma:inputAno")
#     inputAno.click()
#     inputAno.send_keys(Keys.CONTROL, 'a')
#     inputAno.send_keys('2021')
#     botaoSemestre = driver.find_element(By.XPATH,
#         '//*[@id="formTurma:inputPeriodo"]/option[2]')
#     botaoSemestre.click()

# Selecionando a unidade especificada (FGA)
def selecionarUnidade():
    botaoUnidade = driver.find_element(By.ID, 'formTurma:inputDepto')
    botaoFGA = driver.find_element(By.XPATH,
                                   '//*[@id="formTurma:inputDepto"]/option[79]')
    botaoUnidade.click()
    botaoFGA.click()

# Buscando a listagem na unidade selecionada e no semestre especificado
def acionarBotaoBuscar():
    botaoBuscar = driver.find_element(By.NAME,
                                      'formTurma:j_id_jsp_1370969402_11')
    botaoBuscar.click()

# Realiza a contagem da quantidade de vagas disponíveis
# e as imprime conforme a turma em questão.
def verificaVagas():
    contadorDocentes = 0
    contadorVagas = 0
    element1 = driver.find_elements(By.XPATH,
                                    "//td[@style='text-align: center;']")  # lista com todas as quantidades de vagas disponíveis
    for x in element1:
        resto = contadorVagas % 2
        vagas = x.get_attribute('innerHTML')
        if resto == 0:
            vagasOfertadas = int(vagas, base=10)
        else:
            disciplina = driver.find_elements(By.XPATH,
                                              "//td[@class='nome']")[contadorDocentes]
            turma = disciplina.get_attribute('innerHTML')
            numeroAlunos = int(vagas, base=10)
            vagasDisponiveis = vagasOfertadas - numeroAlunos
            print(f'Vagas Disponiveis em {turma}: {vagasDisponiveis}')
            contadorDocentes += 1
        contadorVagas += 1
    return contadorVagas

def fecharJanela():
    driver.quit()

def main():
    acessarURL()
    driver.implicitly_wait(6)
    selecionarNivelEnsino()
    selecionarUnidade()
    # selecionarSemestre()
    acionarBotaoBuscar()
    contadorVagas = verificaVagas()
    print(f'Numero de Turmas encontradas: {contadorVagas/2}')
    fecharJanela()

main()
```
Comentamos a função que é usada para selecionar um semestre em específico justamente porque o intuito do projeto é fazer o scraping dos dados mais recentes fornecidos pelo SIGAA, contudo a função foi utilizada para verificar se é feito, de fato,  a subtração de vagas ofertadas pelas vagas ocupadas em semestres onde os dados já estão devidamente consolidados.
Foram feitas algumas alterações referentes ao "find_element_by...", uma vez que esse modo de utilizar o "finders" está obsoleto (ou deprecated). Portanto trocamos por "find_element(By...)", onde pode ser encontrado na devida [documentação do Metabase](https://www.selenium.dev/pt-br/documentation/webdriver/elements/finders/).

**Comment by gabrielm2q** [comment]
Subi a versão comentada do código na branch "feature/(#93)-scraping-vagas-disponiveis".

**Comment by gabrielm2q** [comment]
A tarefa "Contar a quantidade de vagas disponíveis, por disciplina, que existem" exige uma estruturação do código que pode levar um tempo superior ao de uma _sprint_, sendo que a separação dos dados, pode ser feita de melhor forma em um momento posterior.
Destarte, talvez seja interessante a criação de uma nova _issue_ para tal.

**Comment by guibrbs** [comment]
Adicionamos a funcionalidade de contar a quantidade de vagas disponíveis no geral.
```
def verificaVagas():
    contadorDocentes = 0
    contadorVagas = 0
    vagasTotais = 0
    element1 = driver.find_elements(By.XPATH,
                                    "//td[@style='text-align: center;']")  # lista com todas as quantidades de vagas disponíveis
    for x in element1:
        resto = contadorVagas % 2
        vagas = x.get_attribute('innerHTML')
        if resto == 0:
            vagasOfertadas = int(vagas, base=10)
        else:
            disciplina = driver.find_elements(By.XPATH,
                                              "//td[@class='nome']")[contadorDocentes]
            turma = disciplina.get_attribute('innerHTML')
            numeroAlunos = int(vagas, base=10)
            vagasDisponiveis = vagasOfertadas - numeroAlunos
            vagasTotais += vagasDisponiveis
            print(f'Vagas Disponiveis em {turma}: {vagasDisponiveis}')
            contadorDocentes += 1
        contadorVagas += 1
    print(f'Numero total de vagas disponíveis: {vagasTotais}')
    return contadorVagas
```
Onde é armazenado em "vagasTotais" e posteriormente é apresentado no console o seu número.
### Contribuidores
@guigudf 
@gabrielm2q

**Comment by gabrielm2q** [comment]
@Mateusvff poderia revisar, por favor, o código da branch #93?

**Comment by Matheuspleal** [comment]
Foi feita uma leitura do script python da issue #93 chamado 'QtdVagasDisponiveis.py' e nela, não foram encontrados erros que levariam a uma refatoração do código no atual momento.

**Comment by gabrielm2q** [comment]
Foi realizada a correção de um trecho de inicialização do driver que apresentava mensagem de 'descontinuação' (deprecated).
Código pronto para ser adicionado à develop.
